import {lazy,Suspense,useEffect,useRef,useState} from 'react';
import type {Metadata,Project,ProjectStatus,Selection} from '../model';
import {unique,statusNames} from '../model';
import {builtins,core,equipment,readAsset} from '../engine';
import {useDocument} from '../useDocument';
import Canvas from './Canvas';
import Inspector from './Inspector';
const ExportPanel=lazy(()=>import('./ExportPanel'));
export default function Board({metadata,initial,registerFlush}:{metadata:Metadata;initial:Project;registerFlush:(fn:()=>Promise<void>)=>void}){
 const doc=useDocument(metadata,initial),p=doc.project;
 const [selection,setSelection]=useState<Selection>(null),[tab,setTab]=useState<'equipment'|'nature'|'assets'>('equipment'),[connect,setConnect]=useState(false),[source,setSource]=useState<string|null>(null),[playing,setPlaying]=useState(!matchMedia('(prefers-reduced-motion:reduce)').matches),[grid,setGrid]=useState(false),[snap,setSnap]=useState(true),[zoom,setZoom]=useState(100),[time,setTime]=useState(0),[exporting,setExporting]=useState(false),[message,setMessage]=useState(''),[importRole,setImportRole]=useState<'decoration'|'equipment'>('decoration'),[importing,setImporting]=useState(false);
 const importTask=useRef<Promise<void>>(Promise.resolve());
 const file=useRef<HTMLInputElement>(null),replace=useRef<string|null>(null),toastTimer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);
 useEffect(()=>{registerFlush(async()=>{await importTask.current;await doc.flush();});},[doc.flush,registerFlush]);
 useEffect(()=>()=>clearTimeout(toastTimer.current),[]);
 function report(text:string){setMessage(text);clearTimeout(toastTimer.current);toastTimer.current=setTimeout(()=>setMessage(''),6000);}
 function change(fn:(project:Project)=>void){try{doc.commit(fn);}catch(e){report((e as Error).message);}}
 function add(kind:string){if(p.nodes.length>=100){report('الحد الأقصى 100 عنصر');return;}const template=p.nodes.find(n=>n.kind===kind),asset=p.assets[kind]||builtins[kind],id=unique(kind,p.nodes),name=[...equipment,...core.domainCatalog].find(([key])=>key===kind)?.[1]||template?.name||'صورة مستوردة';const ground=kind.startsWith('ground-'),river=kind.startsWith('river'),sunLike=kind.startsWith('sun');let w=ground?512:river?600:sunLike?240:kind==='junction'?8:150,h=ground?512:w*asset.height/asset.width;if(h>180&&!ground&&!river&&!sunLike){w*=180/h;h=180;}const rank=(k:string)=>k.startsWith('sky-')?0:k.startsWith('ground-')?1:k==='hills'?2:k==='platform-iso'?3:-1,rk=rank(kind);if(kind==='sky-night'){w=p.width;h=w*asset.height/asset.width;}else if(kind==='hills'){w=p.width;h=w*asset.height/asset.width;}else if(kind==='platform-iso'){w=Math.min(1400,p.width*.7);h=w*asset.height/asset.width;}let px=p.width/2,py=p.height/2;if(kind==='hills')py=p.height-h/2;if(kind==='platform-iso')py=p.height*.55;if(ground){const base=p.nodes.find(n=>selection?.type==='node'&&n.id===selection.id&&core.isGround(n));if(base){const right=base.x+base.w/2+w/2;if(right+w/2<=p.width+.5){px=right;py=base.y;}else{px=base.x;py=base.y+base.h/2+h/2;}}else{const last=[...p.nodes].reverse().find(core.isGround);if(last){const right=last.x+last.w/2+w/2;if(right+w/2<=p.width+.5){px=right;py=last.y;}else{px=last.x;py=last.y+last.h/2+h/2;}}else{px=w/2;py=h/2;}}}change(project=>{if(ground){const need=Math.ceil(py+h/2),needX=Math.ceil(px+w/2);if(need>project.height)project.height=Math.min(8192,need);if(needX>project.width)project.width=Math.min(8192,needX);}project.assets[kind]=asset;const created=core.node(id,kind,name,px,py,w,h,{role:template?.role??(!builtins[kind]?importRole:undefined),showLabel:kind!=='junction'&&!core.domainCatalog.some(([key])=>key===kind)&&(builtins[kind]?true:template?.role!=='decoration')});if(rk>=0){let at=0;project.nodes.forEach((n,i)=>{const r=rank(n.kind);if(r>=0&&r<=rk)at=i+1;});project.nodes.splice(at,0,created);}else project.nodes.push(created);});setSelection({type:'node',id});}
 const grounds=p.nodes.filter(core.isGround);
 function fillTerrain(){const kindOf=(selection?.type==='node'&&p.nodes.find(n=>n.id===selection.id&&core.isGround(n))?.kind)||grounds[0]?.kind||'ground-grass';change(project=>{const asset=project.assets[kindOf]||builtins[kindOf];project.assets[kindOf]=asset;project.nodes=project.nodes.filter(n=>!(core.isGround(n)&&n.kind===kindOf));const id=unique('terrain',project.nodes);project.nodes.unshift(core.node(id,kindOf,[...core.domainCatalog].find(([k])=>k===kindOf)?.[1]||'الأرض',project.width/2,project.height/2,project.width,project.height,{showLabel:false}));});report('تم ملء البورد بالكامل بالأرض المحددة');}
 function mergeTerrain(){const kindOf=selection?.type==='node'?p.nodes.find(n=>n.id===selection.id&&core.isGround(n))?.kind:undefined;let merged=0,failed=0;change(project=>{const kinds=kindOf?[kindOf]:[...new Set(project.nodes.filter(core.isGround).map(n=>n.kind))];for(const kind of kinds){let list=project.nodes.filter(n=>core.isGround(n)&&n.kind===kind);const touch=(a:typeof list[0],b:typeof list[0])=>Math.abs(a.x-b.x)<=(a.w+b.w)/2+2&&Math.abs(a.y-b.y)<=(a.h+b.h)/2+2;const seen=new Set<string>();for(const start of list){if(seen.has(start.id))continue;const group=[start];seen.add(start.id);for(let i=0;i<group.length;i++)for(const o of list)if(!seen.has(o.id)&&touch(group[i],o)){seen.add(o.id);group.push(o);}if(group.length<2)continue;const x1=Math.min(...group.map(n=>n.x-n.w/2)),x2=Math.max(...group.map(n=>n.x+n.w/2)),y1=Math.min(...group.map(n=>n.y-n.h/2)),y2=Math.max(...group.map(n=>n.y+n.h/2));const area=group.reduce((t,n)=>t+n.w*n.h,0);if(Math.abs(area-(x2-x1)*(y2-y1))>Math.max(4,area*.002)){failed++;continue;}const keep=project.nodes.find(n=>n.id===start.id)!;keep.x=(x1+x2)/2;keep.y=(y1+y2)/2;keep.w=x2-x1;keep.h=y2-y1;const drop=new Set(group.slice(1).map(n=>n.id));project.nodes=project.nodes.filter(n=>!drop.has(n.id));merged+=group.length;}}});report(merged?`تم دمج ${merged} قطعة في مساحات موحدة`+(failed?` — ${failed} مجموعة لا تشكّل مستطيلًا كاملًا`:''):failed?'القطع المتلاصقة لا تشكّل مستطيلًا كاملًا. رتّبها بحيث تملأ مستطيلًا بلا فراغات.':'لا توجد قطع أرض متلاصقة للدمج');}
 function resizeBoard(width:number,height:number){change(project=>{project.width=Math.min(8192,Math.max(100,width));project.height=Math.min(8192,Math.max(100,height));});}
 function remove(){if(!selection)return;change(project=>{if(selection.type==='node'){project.nodes=project.nodes.filter(n=>n.id!==selection.id);project.edges=project.edges.filter(e=>e.from!==selection.id&&e.to!==selection.id);}else project.edges=project.edges.filter(e=>e.id!==selection.id);});setSelection(null);setSource(null);}
 function duplicate(){const item=p.nodes.find(n=>selection?.type==='node'&&n.id===selection.id);if(!item)return;if(p.nodes.length>=100){report('الحد الأقصى 100 عنصر');return;}const id=unique(item.kind,p.nodes);change(project=>project.nodes.push({...item,id,x:Math.min(project.width-item.w/2,item.x+30),y:Math.min(project.height-item.h/2,item.y+30)}));setSelection({type:'node',id});}
 function connectNode(id:string){const target=p.nodes.find(n=>n.id===id)!;if(!core.canConnect(target)){report('عناصر الطبيعة للعرض فقط ولا تقبل الربط');return;}if(!source){setSource(id);setSelection({type:'node',id});return;}if(source===id){report('اختر عنصرًا آخر ليكون الهدف');return;}if(p.edges.length>=200){report('الحد الأقصى 200 رابط');return;}const from=p.nodes.find(n=>n.id===source);if(!from){setSource(null);return;}const horizontal=Math.abs(target.x-from.x)>Math.abs(target.y-from.y);const edge=core.edge(unique('flow',p.edges),source,id,horizontal?(target.x>from.x?'right':'left'):(target.y>from.y?'bottom':'top'),horizontal?(target.x>from.x?'left':'right'):(target.y>from.y?'top':'bottom'));edge.name=from.name+' ← '+target.name;edge.auto=true;change(project=>project.edges.push(edge));setSelection({type:'edge',id:edge.id});setSource(null);setConnect(false);}
 async function imported(f:File){setImporting(true);const replacing=replace.current;replace.current=null;try{if(!replacing&&p.nodes.length>=100)throw new Error('الحد الأقصى 100 عنصر');const asset=await readAsset(f),kind='custom-'+crypto.randomUUID(),id=unique(kind,p.nodes);doc.commit(project=>{project.assets[kind]=asset;if(replacing){const n=project.nodes.find(n=>n.id===replacing);if(!n)throw new Error('العنصر لم يعد موجودًا');n.role=core.canConnect(n)?'equipment':'decoration';n.kind=kind;}else{let w=150,h=w*asset.height/asset.width;if(h>180){w*=180/h;h=180;}project.nodes.push(core.node(id,kind,f.name.replace(/\.[^.]+$/,''),project.width/2,project.height/2,w,h,{role:importRole,showLabel:importRole==='equipment'}));}});if(!replacing)setSelection({type:'node',id});setTab('assets');report('تم استيراد الصورة وحفظها ضمن أصول المشروع');}catch(e){report((e as Error).message);}finally{setImporting(false);}}
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if((e.target as Element).closest('input,textarea,select,dialog'))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();if(e.shiftKey)doc.redo();else doc.undo();}else if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();remove();}else if(e.key==='Escape'){setConnect(false);setSource(null);setSelection(null);}};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey);});
 useEffect(()=>{if(selection&&!(selection.type==='node'?p.nodes:p.edges).some(n=>n.id===selection.id))setSelection(null);},[p,selection]);
 const catalog=tab==='equipment'?equipment:tab==='nature'?core.domainCatalog:Object.keys(p.assets).filter(k=>!builtins[k]).map(k=>[k,p.nodes.find(n=>n.kind===k)?.name||k]);
 const stateLabel={saved:'محفوظ في المجلد',dirty:'تغييرات غير محفوظة',saving:'جارٍ الحفظ…',error:'تعذر الحفظ'}[doc.saveState];
 return <><div className="board-heading"><div className="board-identity"><a href="#domain">المشاريع</a><span>/</span><h1>{p.title}</h1><span className={'save-state '+doc.saveState} role="status">{stateLabel}</span></div><div className="button-row"><select aria-label="حالة المشروع" value={doc.status} onChange={e=>doc.setStatus(e.target.value as ProjectStatus)}>{Object.entries(statusNames).map(([key,name])=><option value={key} key={key}>{name}</option>)}</select><button disabled={doc.saveState==='saving'} onClick={()=>void doc.flush().catch(e=>report(e.message))}>حفظ الآن</button><button className="primary" onClick={()=>setExporting(true)}>معاينة وتصدير Lottie</button></div></div>{doc.saveError&&<div className="global-error" role="alert">{doc.saveError}<button onClick={()=>void doc.flush().catch(e=>report(e.message))}>إعادة الحفظ</button></div>}
 <main className="board-layout"><aside className="library"><div className="panel-heading"><span className="eyebrow">بناء المشهد</span><h2>المكتبة</h2></div><div className="tabs" aria-label="نوع المكتبة">{([['equipment','عناصر'],['nature','طبيعة'],['assets','أصولي']] as const).map(([key,label])=><button key={key} aria-pressed={tab===key} onClick={()=>setTab(key)}>{label}</button>)}</div><div className="palette">{catalog.map(([kind,name])=><button key={kind} onClick={()=>add(kind)} title={'إضافة '+name}><img src={(p.assets[kind]||builtins[kind]).src} alt=""/><span>+ {name}</span></button>)}</div>{!catalog.length&&<p className="muted">استورد صورة لتظهر ضمن أصول هذا المشروع.</p>}{tab==='nature'&&<p className="muted">أرض وشمس ومياه وأشجار. عناصر طبيعية لا تقبل الربط. كل «أرض» تُضاف ملاصقة للقطعة السابقة بنفس نسيج الخامة، ثم «دمج الأراضي» يجمعها في مساحة واحدة.</p>}<section className="import-section"><label>نوع الصورة<select value={importRole} onChange={e=>setImportRole(e.target.value as 'equipment'|'decoration')}><option value="decoration">طبيعة / ديكور</option><option value="equipment">عنصر قابل للربط</option></select></label><button className="wide" disabled={importing} onClick={()=>{replace.current=null;file.current?.click();}}>{importing?'جارٍ الاستيراد…':'+ استيراد صورة'}</button><small className="muted">SVG · PNG · JPEG · GIF · WebP</small><input ref={file} type="file" hidden accept=".svg,.png,.jpg,.jpeg,.gif,.webp" onChange={e=>{const f=e.target.files?.[0];if(f)importTask.current=imported(f);e.target.value='';}}/></section><section className="layers"><div className="section-heading"><h3>الطبقات</h3><span className="count">{p.nodes.length+p.edges.length}</span></div>{p.nodes.length===0&&<p className="muted">العناصر والروابط ستظهر هنا.</p>}{(['node','edge'] as const).map(type=>(type==='node'?p.nodes:p.edges).map(item=><button className="layer" key={type+item.id} aria-pressed={selection?.id===item.id&&selection.type===type} onClick={()=>setSelection({type,id:item.id})}><i className={'state-dot '+item.state}/><span>{item.name}</span><small>{type==='node'?'عنصر':'رابط'}</small></button>))}</section></aside>
 <section className="board-center"><div className="board-toolbar"><div className="button-row"><button title="تراجع (⌘/Ctrl Z)" aria-label="تراجع" disabled={!doc.past.length} onClick={doc.undo}>↶</button><button title="إعادة (⌘/Ctrl Shift Z)" aria-label="إعادة" disabled={!doc.future.length} onClick={doc.redo}>↷</button><button aria-pressed={connect} onClick={()=>{setConnect(!connect);setSource(null);}}>↗ ربط</button><button onClick={()=>setSelection(null)}>إعدادات البورد</button><select aria-label="حجم البورد" value="" onChange={e=>{const v=e.target.value;if(!v)return;const [w,h]=v.split('x').map(Number);resizeBoard(w,h);}}><option value="">مساحة البورد: {p.width}×{p.height}</option>{[[1600,1000],[2400,1500],[3200,2000],[4800,3000],[6400,4000]].map(([w,h])=><option key={w} value={w+'x'+h}>{w} × {h}</option>)}</select><button title="زيادة عرض البورد 400" onClick={()=>resizeBoard(p.width+400,p.height)}>+ عرض</button><button title="زيادة ارتفاع البورد 400" onClick={()=>resizeBoard(p.width,p.height+400)}>+ ارتفاع</button><button title="ملء البورد بالأرض" onClick={fillTerrain}>▦ ملء بالأرض</button><button title="دمج قطع الأرض المتلاصقة" disabled={grounds.length<2} onClick={mergeTerrain}>⧉ دمج الأراضي</button></div><div className="button-row"><label className="toggle"><input type="checkbox" checked={snap} onChange={e=>setSnap(e.target.checked)}/>محاذاة</label><label className="toggle"><input type="checkbox" checked={grid} onChange={e=>setGrid(e.target.checked)}/>شبكة</label><select aria-label="تكبير البورد" value={zoom} onChange={e=>setZoom(Number(e.target.value))}><option value={100}>ملاءمة</option><option value={125}>125%</option><option value={150}>150%</option><option value={200}>200%</option><option value={300}>300%</option><option value={400}>400%</option></select></div></div><Canvas project={p} selection={selection} select={setSelection} commit={change} connect={connect} connectNode={connectNode} grid={grid} snap={snap} playing={playing} time={time} zoom={zoom} report={report}/><div className="canvas-footer"><span>{connect?(source?'اختر العنصر الهدف.':'اختر العنصر المصدر.'):'اسحب العناصر، أو اختر عنصرًا لتعديل خصائصه.'}</span><span dir="ltr">{p.width} × {p.height}</span></div><div className="timeline"><div><span className="eyebrow">الحركة</span><strong>معاينة خطوط التدفق</strong></div><button aria-pressed={playing} onClick={()=>setPlaying(!playing)}>{playing?'Ⅱ إيقاف':'▶ تشغيل'}</button><input aria-label="وقت معاينة البورد" type="range" min={0} max={20} step={.05} value={time} onChange={e=>{setPlaying(false);setTime(Number(e.target.value));}}/><output dir="ltr">{time.toFixed(2)} s</output></div><p className="board-note">معاينة Lottie تشغّل الملف النهائي وتوضّح اختلافات تصدير الصور المتحركة والنصوص.</p><details className="storage-details"><summary>مكان حفظ المشروع</summary><code dir="ltr">{metadata.folder}</code></details></section>
 <Inspector project={p} selection={selection} change={change} remove={remove} duplicate={duplicate} report={report} replace={()=>{if(selection?.type==='node'){replace.current=selection.id;file.current?.click();}}}/></main>{message&&<div role="status" className="toast">{message}</div>}{exporting&&<Suspense fallback={<div className="toast" role="status">جارٍ تحميل مشغّل Lottie…</div>}><ExportPanel project={p} initialTime={time} onClose={()=>setExporting(false)}/></Suspense>}</>;
}
