import {useLayoutEffect,useRef,useState} from 'react';
import type {Project,Selection} from '../model';
import {copyProject} from '../model';
import {core} from '../engine';
interface Props {project:Project;selection:Selection;select:(s:Selection)=>void;commit:(fn:(p:Project)=>void)=>void;connect:boolean;connectNode:(id:string)=>void;grid:boolean;snap:boolean;playing:boolean;time:number;zoom:number;report:(s:string)=>void}
export default function Canvas({project,selection,select,commit,connect,connectNode,grid,snap,playing,time,zoom,report}:Props){
 const ref=useRef<SVGSVGElement>(null),drag=useRef<{type:'node'|'waypoint';id:string;index?:number;dx:number;dy:number;value?:number[]}|null>(null);const [preview,setPreview]=useState<Project|null>(null);
 useLayoutEffect(()=>{const svg=ref.current;if(!svg)return;const rendered=core.render(preview||project,{editable:true,selection,grid,animate:playing,time});svg.setAttribute('viewBox',rendered.getAttribute('viewBox')!);svg.replaceChildren(...rendered.childNodes);},[project,preview,selection,grid,playing,time]);
 const coord=(event:React.PointerEvent)=>new DOMPoint(event.clientX,event.clientY).matrixTransform(ref.current!.getScreenCTM()!.inverse());
 const end=()=>{const d=drag.current;drag.current=null;setPreview(null);if(!d?.value)return;try{commit(p=>{if(d.type==='node'){const n=p.nodes.find(n=>n.id===d.id);if(n){[n.x,n.y]=d.value!;for(const e of p.edges)if(e.from===n.id||e.to===n.id)e.auto=true;}}else{const e=p.edges.find(e=>e.id===d.id);if(e)e.waypoints[d.index!]=d.value!;}});}catch(e){report((e as Error).message);}};
 return <div className="canvas-scroll"><div style={{width:zoom+'%',minWidth:'100%'}}><svg ref={ref} data-testid="scene-canvas" className="scene-canvas" aria-label="بورد المجال" onPointerDown={e=>{if(e.button!==0)return;const target=e.target as Element,node=target.closest('[data-node]'),edge=target.closest('[data-edge]'),handle=target.closest('[data-waypoint]');const point=coord(e);if(handle){const id=handle.getAttribute('data-edge-id')!;drag.current={type:'waypoint',id,index:Number(handle.getAttribute('data-waypoint')),dx:0,dy:0};}else if(node){const id=node.getAttribute('data-node')!;if(connect){connectNode(id);return;}const n=project.nodes.find(n=>n.id===id)!;select({type:'node',id});drag.current={type:'node',id,dx:point.x-n.x,dy:point.y-n.y};}else{select(edge?{type:'edge',id:edge.getAttribute('data-edge')!}:null);return;}ref.current!.setPointerCapture(e.pointerId);e.preventDefault();}} onPointerMove={e=>{const d=drag.current;if(!d)return;const pt=coord(e),round=(v:number)=>snap?Math.round(v/10)*10:Math.round(v),p=copyProject(project);if(d.type==='node'){const n=p.nodes.find(n=>n.id===d.id)!;n.x=Math.max(n.w/2,Math.min(p.width-n.w/2,round(pt.x-d.dx)));n.y=Math.max(n.h/2,Math.min(p.height-n.h/2,round(pt.y-d.dy)));d.value=[n.x,n.y];for(const edge of p.edges)if(edge.from===n.id||edge.to===n.id)edge.auto=true;}else{d.value=[round(pt.x),round(pt.y)];p.edges.find(e=>e.id===d.id)!.waypoints[d.index!]=d.value;}setPreview(p);}} onPointerUp={end} onPointerCancel={()=>{drag.current=null;setPreview(null);}}/></div>{!project.nodes.length&&<div className="canvas-empty"><h2>البورد جاهزة</h2><p>أضف أول عنصر من المكتبة، أو استورد صورة.</p></div>}</div>;
}
