import {useEffect,useRef,useState} from 'react';
import lottie from 'lottie-web';
import type {AnimationItem} from 'lottie-web';
import type {Project,LottieData} from '../model';
import {core,checkBounds,exportProject,download} from '../engine';
import type {ExportFormat} from '../engine';
export default function ExportPanel({project,initialTime,onClose}:{project:Project;initialTime:number;onClose:()=>void}){
 const dialog=useRef<HTMLDialogElement>(null),host=useRef<HTMLDivElement>(null),player=useRef<AnimationItem|null>(null),generation=useRef(0);const [transparent,setTransparent]=useState(false),[scale,setScale]=useState(2),[time,setTime]=useState(initialTime),[data,setData]=useState<LottieData|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[ready,setReady]=useState(false),[playing,setPlaying]=useState(!matchMedia('(prefers-reduced-motion:reduce)').matches),[frame,setFrame]=useState(0);
 useEffect(()=>{dialog.current?.showModal();return()=>{generation.current++;player.current?.destroy();};},[]);
 useEffect(()=>{const id=++generation.current;setBusy(true);setError('');setReady(false);setData(null);check();async function check(){try{checkBounds(project);const result=await core.lottie(project,{transparent});if(id===generation.current)setData(result);}catch(e){if(id===generation.current)setError((e as Error).message);}finally{if(id===generation.current)setBusy(false);}}},[project,transparent]);
 useEffect(()=>{if(!data||!host.current)return;const animation=lottie.loadAnimation({container:host.current,renderer:'svg',loop:true,autoplay:playing,animationData:structuredClone(data)});player.current=animation;const loaded=()=>setReady(true),failed=()=>setError('تعذر تشغيل ملف Lottie الناتج');animation.addEventListener('DOMLoaded',loaded);animation.addEventListener('data_failed',failed);animation.addEventListener('error',failed);return()=>{animation.destroy();player.current=null;};},[data]);
 const warnings:string[]=[];if(project.nodes.some(n=>n.state!=='hidden'&&project.assets[n.kind]?.src.startsWith('data:image/gif')))warnings.push('صور GIF تُصدّر كلقطة ثابتة. حركتها الأصلية لا تنتقل إلى Lottie.');if(project.nodes.some(n=>n.state!=='hidden'&&project.assets[n.kind]?.src.startsWith('data:image/webp')))warnings.push('إذا كانت صورة WebP متحركة، يُصدّر منها إطار ثابت.');if(project.nodes.some(n=>n.state!=='hidden'&&n.showLabel!==false))warnings.push('النصوص والبيانات تُضمّن كصور للحفاظ على العربية والخطوط. القيم ثابتة وقت التصدير.');
 async function save(format:ExportFormat){setBusy(true);setError('');try{const blob=format==='lottie'&&data?new Blob([JSON.stringify(data)],{type:'application/json'}):await exportProject(project,format,{transparent,scale,time});download(blob,project.title,format);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <dialog ref={dialog} className="export-dialog" onCancel={onClose} onClose={onClose}><div className="dialog-header"><div><span className="eyebrow">الملف النهائي</span><h2>معاينة وتصدير Lottie</h2></div><button aria-label="إغلاق المعاينة" onClick={onClose}>×</button></div><p className="muted">هذه المعاينة تشغّل JSON الناتج باستخدام lottie-web، وليست صورة البورد.</p><div className={'lottie-preview '+(transparent?'checker':'')} ref={host}/>{busy&&!data&&<p role="status">جارٍ تجهيز الملف والأصول…</p>}{error&&<div role="alert" className="error">{error}</div>}{data&&<div className="preview-controls"><button disabled={!ready} onClick={()=>{if(playing)player.current?.pause();else player.current?.play();setPlaying(!playing);}}>{playing?'إيقاف':'تشغيل'}</button><input aria-label="إطار معاينة Lottie" type="range" min={0} max={data.op-1} value={frame} onChange={e=>{const n=Number(e.target.value);setFrame(n);setPlaying(false);player.current?.goToAndStop(n,true);}}/><span dir="ltr">{((data.op-data.ip)/data.fr).toFixed(1)}s · {data.fr} fps · {data.w} × {data.h}</span></div>}<label className="toggle"><input type="checkbox" checked={transparent} onChange={e=>setTransparent(e.target.checked)}/>خلفية شفافة</label>{warnings.length>0&&<div className="export-notes"><h3>ما يحتويه ملف Lottie</h3><ul>{warnings.map(w=><li key={w}>{w}</li>)}<li>العناصر الإيزومترية الجديدة والشمس المتحركة تُحفظ كرسومات متجهية، وتنتقل حركة الروابط والمياه إلى الملف. اختبر الملف أيضًا على مشغّل التطبيق الذي سيعرضه.</li></ul></div>}<button className="primary wide" disabled={busy||!ready||!!error} onClick={()=>void save('lottie')}>تنزيل ملف Lottie .json</button><details className="other-exports"><summary>المشروع وصيغ التصدير الأخرى</summary><div className="field-grid"><label>دقة PNG<select value={scale} onChange={e=>setScale(Number(e.target.value))}><option value={1}>1×</option><option value={2}>2×</option><option value={3}>3×</option></select></label><label>وقت اللقطة (ثانية)<input type="number" min={0} max={20} step={.05} value={time} onChange={e=>setTime(Math.max(0,Math.min(20,Number(e.target.value))))}/></label></div><div className="button-row">{(['project','html','svg','png'] as ExportFormat[]).map(f=><button disabled={busy} key={f} onClick={()=>void save(f)}>{f==='project'?'مشروع قابل للتحرير':f.toUpperCase()}</button>)}</div></details></dialog>;
}
