import {useEffect,useState} from 'react';
import type {Project,SceneNode,SceneEdge,Selection,ItemState} from '../model';
import {core} from '../engine';
type Value=string|number;
function Field({label,value,onChange,type='text',min,max,step}: {label:string;value:Value;onChange:(v:Value)=>void;type?:string;min?:number;max?:number;step?:number|string}){const [draft,setDraft]=useState(String(value??''));useEffect(()=>setDraft(String(value??'')),[value]);return <label>{label}<input type={type} value={draft} min={min} max={max} step={step} onChange={e=>setDraft(e.target.value)} onBlur={e=>{if(!e.target.checkValidity()||(type==='number'&&draft==='')){setDraft(String(value));return;}const next=type==='number'?Number(draft):draft;if(next!==value)onChange(next);}} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur();}}/></label>;}
function Toggle({label,value,onChange}:{label:string;value:boolean;onChange:(v:boolean)=>void}){return <label className="toggle"><input type="checkbox" checked={value} onChange={e=>onChange(e.target.checked)}/>{label}</label>;}
function Select({label,value,options,onChange}:{label:string;value:string;options:[string,string][];onChange:(v:string)=>void}){return <label>{label}<select value={value} onChange={e=>onChange(e.target.value)}>{options.map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label>;}
const ports:[string,string][]=[['top','أعلى'],['bottom','أسفل'],['left','يسار'],['right','يمين'],['center','المنتصف']];
export default function Inspector({project,selection,change,remove,duplicate,replace,report}:{project:Project;selection:Selection;change:(fn:(p:Project)=>void)=>void;remove:()=>void;duplicate:()=>void;replace:()=>void;report:(s:string)=>void}){
 const node=selection?.type==='node'?project.nodes.find(n=>n.id===selection.id):undefined,edge=selection?.type==='edge'?project.edges.find(e=>e.id===selection.id):undefined,item=node||edge;
 const patch=(key:string,value:Value|boolean)=>change(p=>{const list=node?p.nodes:p.edges;const target=list.find(n=>n.id===item?.id);if(target){Object.assign(target,{[key]:value});if(node&&['x','y','w','h'].includes(key))for(const e of p.edges)if(e.from===node.id||e.to===node.id)e.auto=true;}});
 const nf=(label:string,key:keyof SceneNode,type='text',min?:number,max?:number,step?:number|string)=><Field key={key} label={label} value={node![key] as Value} type={type} min={min} max={max} step={step} onChange={v=>patch(key,v)}/>;
 const ef=(label:string,key:keyof SceneEdge,type='text',min?:number,max?:number,step?:number|string)=><Field key={key} label={label} value={edge![key] as Value} type={type} min={min} max={max} step={step} onChange={v=>patch(key,v)}/>;
 return <aside className="inspector" aria-label="الخصائص"><div className="panel-heading"><span className="eyebrow">الخصائص</span><h2>{node?'العنصر المحدد':edge?'الرابط المحدد':'إعدادات البورد'}</h2>{item&&<code dir="ltr">{item.id}</code>}</div>
 {!item?<><Field label="اسم المشروع" value={project.title} onChange={v=>change(p=>{p.title=String(v);})}/><div className="field-grid"><Field label="العرض" type="number" min={100} max={4096} value={project.width} onChange={v=>change(p=>{p.width=Number(v);})}/><Field label="الارتفاع" type="number" min={100} max={4096} value={project.height} onChange={v=>change(p=>{p.height=Number(v);})}/></div><Field label="خلفية البورد" type="color" value={project.background} onChange={v=>change(p=>{p.background=String(v);})}/><button className="wide" onClick={()=>change(p=>{core.fit(p);})}>ملاءمة مساحة البورد</button><div className="help"><h3>ابدأ من المكتبة</h3><p>أضف عناصر الطاقة والطبيعة، ثم اسحبها إلى موضعها. لربط عنصرين فعّل «ربط» واختر المصدر ثم الهدف.</p><p>الطبيعة للعرض فقط. معاينة Lottie تعرض الملف الناتج فعلًا قبل تنزيله.</p></div></>:<><div className="state-switch" aria-label="حالة العنصر">{(['active','inactive','hidden'] as ItemState[]).map(s=><button key={s} aria-pressed={item.state===s} onClick={()=>patch('state',s)}>{({active:'نشط',inactive:'متوقف',hidden:'مخفي'})[s]}</button>)}</div>
 {node?<>{nf('اسم العنصر','name')}<span className="badge">{core.canConnect(node)?'عنصر قابل للربط':'طبيعة / ديكور، بدون ربط'}</span><section><h3>الموضع والحجم</h3><div className="field-grid">{nf('X','x','number',-4096,8192)}{nf('Y','y','number',-4096,8192)}{nf('العرض','w','number',1,4096)}{nf('الارتفاع','h','number',1,4096)}</div><button className="wide" onClick={replace}>استبدال صورة العنصر</button></section><section><h3>البيانات</h3><div className="field-grid">{nf('القيمة','value','number',undefined,undefined,'any')}{nf('الوحدة','unit')}{nf('التيار','current','number',undefined,undefined,'any')}{nf('وحدة التيار','currentUnit')}{nf('الكفاءة %','efficiency','number',0,100,'any')}</div>{nf('نص الحالة','status')}</section><section><h3>عرض البيانات</h3><Toggle label="إظهار بيانات العنصر" value={node.showLabel!==false} onChange={v=>patch('showLabel',v)}/><Select label="طريقة العرض" value={node.labelStyle||'text'} options={[["text","نص"],["card","بطاقة"]]} onChange={v=>patch('labelStyle',v)}/><div className="checks">{(['showName','showValue','showStatus'] as const).map((key,i)=><Toggle key={key} label={['الاسم','القيمة والوحدة','الحالة'][i]} value={node[key]!==false} onChange={v=>patch(key,v)}/>)}<Toggle label="التيار والكفاءة" value={node.showDetails} onChange={v=>patch('showDetails',v)}/></div><Select label="موضع البيانات" value={node.labelSide} options={ports.slice(0,4)} onChange={v=>patch('labelSide',v)}/><div className="field-grid">{nf('المسافة','labelGap','number',0,200)}{nf('حجم الخط','fontSize','number',8,60)}</div>{nf('لون القيمة','color','color')}</section><div className="button-row"><button onClick={duplicate}>تكرار</button><button onClick={()=>change(p=>{const i=p.nodes.findIndex(n=>n.id===node.id);p.nodes.push(...p.nodes.splice(i,1));})}>للأمام</button><button onClick={()=>change(p=>{const i=p.nodes.findIndex(n=>n.id===node.id);p.nodes.unshift(...p.nodes.splice(i,1));})}>للخلف</button></div></>:null}
 {edge?<>{ef('اسم الرابط','name')}<Select label="المصدر" value={edge.from} options={project.nodes.filter(core.canConnect).map(n=>[n.id,n.name])} onChange={v=>patch('from',v)}/><Select label="الهدف" value={edge.to} options={project.nodes.filter(core.canConnect).map(n=>[n.id,n.name])} onChange={v=>patch('to',v)}/><div className="field-grid"><Select label="منفذ المصدر" value={edge.sourcePort} options={ports} onChange={v=>patch('sourcePort',v)}/><Select label="منفذ الهدف" value={edge.targetPort} options={ports} onChange={v=>patch('targetPort',v)}/></div><section><h3>المظهر والحركة</h3><div className="field-grid">{ef('لون الحركة','color','color')}{ef('لون المسار','trackColor','color')}{ef('عرض الحركة','width','number',.5,30,.5)}{ef('عرض المسار','trackWidth','number',.5,30,.1)}{ef('استدارة الزوايا','radius','number',0,100)}{ef('دورة الحركة (ثانية)','duration','number',.5,20,.1)}</div><Select label="الاتجاه" value={String(edge.direction)} options={[["1","المصدر إلى الهدف"],["-1","الهدف إلى المصدر"]]} onChange={v=>patch('direction',Number(v))}/></section><section><h3>المسار</h3><Toggle label="مسار تلقائي" value={edge.auto} onChange={v=>{change(p=>{const e=p.edges.find(x=>x.id===edge.id)!;if(!v)e.waypoints=core.points(p,e).slice(1,-1);e.auto=v;});}}/>{!edge.auto&&<><p className="muted">اسحب نقاط المسار على البورد، أو اكتب كل نقطة في سطر: x, y.</p><textarea aria-label="نقاط المسار" dir="ltr" key={JSON.stringify(edge.waypoints)} defaultValue={edge.waypoints.map(q=>q.join(', ')).join('\n')} onBlur={event=>{const text=event.target.value.trim();const pts=text?text.split('\n').map(l=>l.split(',').map(Number)):[];if(!pts.every(q=>q.length===2&&q.every(Number.isFinite))){report('كل سطر يحتاج رقمين مفصولين بفاصلة');return;}change(p=>{p.edges.find(e=>e.id===edge.id)!.waypoints=pts;});}}/><button onClick={()=>change(p=>{const e=p.edges.find(x=>x.id===edge.id)!,pts=core.points(p,e),i=Math.floor((pts.length-1)/2),a=pts[i],b=pts[i+1];e.waypoints.splice(i,0,[(a[0]+b[0])/2,(a[1]+b[1])/2]);})}>إضافة نقطة تحكم</button></>}</section></>:null}<button className="danger wide" onClick={remove}>حذف {node?'العنصر':'الرابط'}</button></>}
 </aside>;
}
