import {useEffect,useRef,useState} from 'react';
import {api} from '../api';
import {core,createProject,builtins} from '../engine';
import {statusNames} from '../model';
import type {Metadata,Project} from '../model';
export default function Projects({onOpen}:{onOpen:(id:string)=>void}){
 const [projects,setProjects]=useState<Metadata[]>([]),[root,setRoot]=useState(''),[name,setName]=useState(''),[layout,setLayout]=useState('blank'),[filter,setFilter]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState('');const file=useRef<HTMLInputElement>(null);
 async function refresh(){setLoading(true);setError('');try{const result=await api.list();setProjects(result.projects);setRoot(result.root);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{void refresh();},[]);
 async function create(p:Project){setBusy(true);setError('');try{core.validate(p);const result=await api.create(p);onOpen(result.metadata.id);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function importFile(f:File){try{if(f.size>25*1024*1024)throw new Error('الحد الأقصى للمشروع 25 MB');const data=JSON.parse(await f.text());const p=core.validate({...data,assets:{...builtins,...data.assets}});await create(p);}catch(e){setError((e as Error).message);}}
 const filtered=projects.filter(p=>p.title.toLowerCase().includes(filter.toLowerCase()));
 return <main className="projects-page"><div className="page-heading"><div><span className="eyebrow">مساحة العمل</span><h1>مشاريع المجال</h1><p>صمّم مشهدك، اربط عناصره، وعاين ملف Lottie قبل التصدير.</p></div><button onClick={()=>file.current?.click()} disabled={busy}>استيراد مشروع .flow.json</button><input ref={file} type="file" accept=".json" hidden onChange={e=>{const f=e.target.files?.[0];if(f)void importFile(f);e.target.value='';}}/></div>
 <form className="create-project" onSubmit={e=>{e.preventDefault();if(name.trim())void create(createProject(layout,name.trim()));}}><div><h2>مشروع جديد</h2><p>يُنشأ مجلد المشروع أولًا، ثم تفتح البورد.</p></div><label>اسم المشروع<input data-testid="project-name" required maxLength={100} value={name} onChange={e=>setName(e.target.value)} placeholder="مثال: محطة الطاقة الشمسية"/></label><label>ابدأ من<select value={layout} onChange={e=>setLayout(e.target.value)}><option value="blank">بورد فارغة</option><option value="domain">مجال الطاقة والطبيعة</option><option value="reference-energy">مشهد الطاقة الإيزومتري · Lottie</option><option value="hybrid">مخطط الطاقة الهجين</option><option value="generator">مولد احتياطي</option><option value="pump">مضخة شمسية</option></select></label><button className="primary" disabled={busy||loading} type="submit">{busy?'جارٍ الإنشاء…':'إنشاء وفتح البورد'}</button></form>
 {error&&<div role="alert" className="error">{error}<button onClick={()=>void refresh()}>إعادة المحاولة</button></div>}
 <div className="section-heading"><h2>المشاريع المحفوظة <span className="count">{projects.length}</span></h2><input aria-label="البحث في المشاريع" value={filter} onChange={e=>setFilter(e.target.value)} placeholder="ابحث عن مشروع…"/><button onClick={()=>void refresh()} disabled={loading}>تحديث</button></div>
 {loading?<p role="status" className="empty-state">جارٍ قراءة مجلدات المشاريع…</p>:filtered.length?<div className="project-list">{filtered.map(p=><article className="project-row" key={p.id}><div className="project-symbol" aria-hidden="true">◇</div><div className="project-info"><h3>{p.title}</h3><p>{p.nodes} عنصر · {p.edges} رابط · {p.assets} أصل</p><small>آخر حفظ {new Date(p.updatedAt).toLocaleString('ar-SA',{dateStyle:'medium',timeStyle:'short'})}</small><details><summary>مجلد المشروع</summary><code dir="ltr">{p.folder}</code></details></div><span className={'badge '+p.status}>{statusNames[p.status]}</span><button onClick={()=>onOpen(p.id)}>فتح البورد ←</button></article>)}</div>:<div className="empty-state"><span aria-hidden="true">◇</span><h3>{filter?'لا توجد نتائج':'مشهدك الأول يبدأ هنا'}</h3><p>{filter?'جرّب اسمًا آخر.':'أنشئ مشروعًا فارغًا أو اختر مشهدًا جاهزًا، ثم أضف العناصر من المكتبة.'}</p></div>}
 <footer className="projects-footer"><span>حفظ محلي في مجلدات فعلية</span><code dir="ltr">{root}</code></footer></main>;
}
