import {test} from 'node:test';
import assert from 'node:assert/strict';
import {chromium} from 'playwright';
import {spawn} from 'node:child_process';
import {mkdtemp,readFile,rm,readdir} from 'node:fs/promises';
import {existsSync} from 'node:fs';
import os from 'node:os';
import path from 'node:path';

test('React project lifecycle, isolated saving, nature rules, GIF and actual Lottie playback', {timeout:120000}, async()=>{
 const folder=await mkdtemp(path.join(os.tmpdir(),'flow-react-test-')),port=8876,base=`http://127.0.0.1:${port}`;
 const server=spawn('python3',['server.py'],{env:{...process.env,FLOW_STUDIO_PORT:String(port),FLOW_STUDIO_PROJECTS:folder},stdio:'pipe'});
 let browser;try{
  for(let i=0;i<60;i++){try{if((await fetch(base+'/api/domain/projects')).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
  const chrome='/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
  browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:existsSync(chrome)?{executablePath:chrome}:{})});
  const page=await browser.newPage({viewport:{width:1600,height:1100}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(base+'/#board');await page.getByRole('heading',{name:'مشاريع المجال'}).waitFor();assert.equal(await page.locator('[data-testid=scene-canvas]').count(),0);
  await page.getByTestId('project-name').fill('اختبار React');await page.getByLabel('ابدأ من').selectOption('domain');await page.getByRole('button',{name:'إنشاء وفتح البورد'}).click();await page.waitForURL(/#board\/[a-f0-9]+/);await page.locator('[data-testid=scene-canvas] [data-node=home]').waitFor();const id=page.url().split('/').at(-1);
  assert.equal((await readdir(folder)).length,1);await page.getByLabel('حالة المشروع').selectOption('active');
  await page.getByRole('button',{name:'↗ ربط',exact:true}).click();await page.locator('[data-node=sun]').click();await page.getByRole('status').filter({hasText:'عناصر الطبيعة'}).waitFor();await page.getByRole('button',{name:'↗ ربط',exact:true}).click();
  const node=page.locator('[data-node=home]'),box=await node.boundingBox();await page.mouse.move(box.x+box.width/2,box.y+20);await page.mouse.down();await page.mouse.move(box.x+box.width/2+35,box.y+45,{steps:6});await page.mouse.up();
  await page.getByLabel('اسم العنصر',{exact:true}).fill('منزل الاختبار');await page.getByLabel('اسم العنصر',{exact:true}).press('Tab');await page.getByRole('button',{name:'حفظ الآن',exact:true}).click();await page.getByRole('status').filter({hasText:'محفوظ في المجلد'}).waitFor();
  let saved=await (await fetch(base+'/api/domain/projects/'+id)).json();assert.equal(saved.metadata.status,'active');assert.equal(saved.project.nodes.find(n=>n.id==='home').name,'منزل الاختبار');assert.notEqual(saved.project.nodes.find(n=>n.id==='home').x,560);
  await page.getByRole('button',{name:'تراجع',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.inspector input')?.value==='المنزل');assert.equal(await page.getByLabel('اسم العنصر',{exact:true}).inputValue(),'المنزل');await page.getByRole('button',{name:'إعادة',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.inspector input')?.value==='منزل الاختبار');assert.equal(await page.getByLabel('اسم العنصر',{exact:true}).inputValue(),'منزل الاختبار');
  await page.locator('[data-node=sun]').click();const chooser=page.waitForEvent('filechooser');await page.getByRole('button',{name:'استبدال صورة العنصر'}).click();await(await chooser).setFiles({name:'sun.gif',mimeType:'image/gif',buffer:Buffer.from('R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7','base64')});await page.getByRole('status').filter({hasText:'تم استيراد الصورة'}).waitFor();
  await page.getByRole('button',{name:'معاينة وتصدير Lottie',exact:true}).click();await page.locator('.lottie-preview svg').waitFor();const downloadButton=page.getByRole('button',{name:'تنزيل ملف Lottie .json'});await downloadButton.waitFor();await page.waitForFunction(()=>!Array.from(document.querySelectorAll('button')).find(b=>b.textContent==='تنزيل ملف Lottie .json')?.disabled,{},{timeout:10000}).catch(async e=>{console.log('Preview diagnostic:',await page.locator('.export-dialog').innerText(),errors);throw e;});assert.match(await page.locator('.export-notes').textContent(),/GIF/);
  const animationBefore=await page.locator('.lottie-preview').innerHTML();await page.waitForTimeout(180);assert.notEqual(await page.locator('.lottie-preview').innerHTML(),animationBefore,'Lottie player must animate actual exported paths');
  const download=page.waitForEvent('download');await downloadButton.click();const exported=await download;const data=JSON.parse(await readFile(await exported.path(),'utf8'));assert.equal(data.fr,30);assert.ok(data.layers.some(l=>l.ty===4));assert.ok(data.layers.some(l=>l.nm.includes('pulse')));assert.ok(data.assets.every(a=>a.p.startsWith('data:image/')));
  await page.getByRole('button',{name:'إغلاق المعاينة'}).click();await page.getByRole('button',{name:'حفظ الآن',exact:true}).click();await page.getByRole('status').filter({hasText:'محفوظ في المجلد'}).waitFor();
  saved=await(await fetch(base+'/api/domain/projects/'+id)).json();assert.equal(saved.project.nodes.find(n=>n.id==='sun').role,'decoration');assert.ok((await readdir(path.join(folder,id,'assets'))).some(f=>f.endsWith('.gif')));
  await page.reload();await page.locator('[data-testid=scene-canvas]').waitFor();assert.equal(await page.getByRole('heading',{name:'اختبار React',exact:true}).count(),1);
  await page.getByRole('button',{name:'أصولي',exact:true}).click();await page.locator('.palette button').first().click();await page.getByRole('button',{name:'حفظ الآن',exact:true}).click();await page.getByRole('status').filter({hasText:'محفوظ في المجلد'}).waitFor();saved=await(await fetch(base+'/api/domain/projects/'+id)).json();assert.equal(saved.project.nodes.at(-1).role,'decoration','Reusing a natural asset must preserve its role');
  // A failed save must keep the active document available and prevent switching projects.
  await page.route('**/api/domain/projects/'+id,route=>route.request().method()==='PUT'?route.fulfill({status:500,contentType:'application/json',body:JSON.stringify({error:'اختبار فشل الحفظ'})}):route.continue());
  await page.getByRole('button',{name:'إعدادات البورد',exact:true}).click();await page.getByLabel('اسم المشروع',{exact:true}).fill('تغيير محفوظ لاحقًا');await page.getByLabel('اسم المشروع',{exact:true}).press('Tab');await page.locator('.board-identity a').click();await page.getByRole('alert').filter({hasText:'اختبار فشل الحفظ'}).first().waitFor();assert.equal(await page.locator('[data-testid=scene-canvas]').count(),1);
  await page.unroute('**/api/domain/projects/'+id);await page.getByRole('button',{name:'حفظ الآن',exact:true}).click();await page.getByRole('status').filter({hasText:'محفوظ في المجلد'}).waitFor();await page.locator('.board-identity a').click();await page.getByRole('heading',{name:'مشاريع المجال'}).waitFor();
  await page.getByTestId('project-name').fill('مشروع مستقل');await page.getByRole('button',{name:'إنشاء وفتح البورد'}).click();await page.locator('[data-testid=scene-canvas]').waitFor();assert.equal(await page.locator('[data-testid=scene-canvas] [data-node]').count(),0);assert.equal(await page.getByRole('button',{name:'تراجع',exact:true}).isDisabled(),true);
  const secondId=page.url().split('/').at(-1);await page.route('**/api/domain/projects/'+id,async route=>{if(route.request().method()==='GET')await new Promise(r=>setTimeout(r,250));await route.continue();});await page.evaluate(old=>{location.hash='#board/'+old;},id);await page.getByRole('status').filter({hasText:'جارٍ فتح مساحة العمل'}).waitFor();await page.evaluate(current=>{location.hash='#board/'+current;},secondId);await page.waitForFunction(()=>!document.querySelector('.route-progress'));await page.waitForTimeout(300);assert.equal(await page.locator('[data-testid=scene-canvas] [data-node]').count(),0);await page.unroute('**/api/domain/projects/'+id);
  await page.screenshot({path:path.join(os.tmpdir(),'flow-react-board.png'),fullPage:true});await page.locator('.board-identity a').click();await page.getByRole('heading',{name:'مشاريع المجال'}).waitFor();await page.screenshot({path:path.join(os.tmpdir(),'flow-react-projects.png'),fullPage:true});assert.deepEqual(errors,[]);
 }finally{await browser?.close();server.kill('SIGTERM');await new Promise(resolve=>server.once('exit',resolve));await rm(folder,{recursive:true,force:true});}
});
