/* Flow Studio rendering/export engine. No dependencies. */
(function (global) {
'use strict';
const NS='http://www.w3.org/2000/svg', STATES=['active','inactive','hidden'];
const clone=v=>JSON.parse(JSON.stringify(v));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
const num=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const rnd=v=>Math.round(v*1000)/1000;
function element(tag,attrs={},text){const e=document.createElementNS(NS,tag);for(const[k,v]of Object.entries(attrs))if(v!==undefined)e.setAttribute(k,v);if(text!==undefined)e.textContent=text;return e;}
function svgAsset(body,w=100,h=100){return{src:'data:image/svg+xml;base64,'+btoa(unescape(encodeURIComponent(`<svg xmlns="${NS}" viewBox="0 0 ${w} ${h}">${body}</svg>`))),width:w,height:h};}
const extraAssets={
 junction:svgAsset('<circle cx="50" cy="50" r="25" fill="#6a8bf2"/>'),
 generator:svgAsset('<ellipse cx="52" cy="86" rx="42" ry="7" fill="#dbe3eb"/><path d="M12 36 26 26H76L88 38V74L76 84H24L12 73Z" fill="#a2b1bf"/><path d="M12 36H75V84H24L12 73Z" fill="#718699"/><path d="M75 36 88 38V74L75 84Z" fill="#445d72"/><rect x="21" y="45" width="44" height="28" rx="3" fill="#ced7df"/><path d="M27 49V67M33 49V67M39 49V67M45 49V67" stroke="#7d8e9f" stroke-width="3"/><rect x="54" y="49" width="7" height="7" rx="1" fill="#5698af"/><path d="M65 26V14H74V26" fill="#576d80"/><path d="m29 84 0 6m40-6v6" stroke="#51677b" stroke-width="5"/>'),
 pump:svgAsset('<ellipse cx="50" cy="85" rx="40" ry="7" fill="#dbe3eb"/><path d="M24 34H60V67H24Z" fill="#6aa9c5"/><path d="M59 34 75 41V70L59 67Z" fill="#376d8c"/><ellipse cx="25" cy="50" rx="16" ry="18" fill="#9ac8da"/><ellipse cx="25" cy="50" rx="10" ry="12" fill="#5e96b1"/><path d="M15 67V79H70V70" fill="#6b8093"/><path d="M71 49H87V32" fill="none" stroke="#98c8dd" stroke-width="10"/><path d="M43 34V16H63" fill="none" stroke="#6da8c2" stroke-width="9"/>')
};
// Embedded nature artwork stays available offline and in every export.
const domainCatalog=[['ground-grass','أرض عشبية'],['ground-sand','أرض رملية'],['ground-stone','أرض صخرية'],['ground-soil','تربة'],['ground-concrete','خرسانة / أسفلت'],['platform-iso','منصة isometric'],['hills','تلال'],['sky-night','سماء ليلية'],['sun','شمس'],['sun-soft','شمس هادئة'],['moon','هلال'],['moon-full','قمر كامل'],['river','نهر متعرج'],['river-wide','نهر واسع'],['tree','شجرة'],['pine','شجرة صنوبر'],['forest','غابة']];
function groundTexture(base,patch,grain,freq,extra=''){const f=(id,fr,oct,seed,m)=>`<filter id="${id}" x="0" y="0" width="100%" height="100%" color-interpolation-filters="sRGB"><feTurbulence type="fractalNoise" baseFrequency="${fr}" numOctaves="${oct}" seed="${seed}" stitchTiles="stitch"/><feColorMatrix type="matrix" values="${m}"/></filter>`;return svgAsset(`<defs>${f('p',freq,4,7,patch)}${f('g','.85',2,3,grain)}</defs><rect width="512" height="512" fill="${base}"/><rect width="512" height="512" filter="url(#p)"/><rect width="512" height="512" filter="url(#g)" opacity=".9"/>${extra}`,512,512);}
 const blades=(c,n)=>{let r=11,o='';const rand=()=>(r=(r*16807)%2147483647)/2147483647;for(let i=0;i<n;i++){const x=rand()*512,y=rand()*512,l=5+rand()*9,a=(rand()-.5)*50;for(const dx of [-512,0,512])for(const dy of [-512,0,512]){const X=x+dx,Y=y+dy;if(X<-20||X>532||Y<-20||Y>532)continue;o+=`<path d="M${X.toFixed(1)} ${Y.toFixed(1)}l${(l*Math.sin(a*Math.PI/180)).toFixed(1)} ${(-l).toFixed(1)}" stroke="${c[i%c.length]}" stroke-width="1.3" stroke-linecap="round" opacity=".55"/>`;}}return o;};
 const terrain=kind=>({grass:()=>groundTexture('#4d7a36','.2 0 0 0 .2 0 .3 0 0 .33 0 0 .12 0 .15 0 0 0 0 1','0 0 0 0 .04 0 0 0 0 .1 0 0 0 0 .03 1.1 0 0 0 -.45',.007,blades(['#8dbd5a','#2f5a24','#a7c96a'],420)),sand:()=>groundTexture('#cdb384','.22 0 0 0 .5 .22 0 0 0 .4 .2 0 0 0 .28 0 0 0 0 1','0 0 0 0 .45 0 0 0 0 .34 0 0 0 0 .2 1.4 0 0 0 -.6',.012),stone:()=>groundTexture('#7b8288','.3 0 0 0 .3 .3 0 0 0 .32 .3 0 0 0 .34 0 0 0 0 1','0 0 0 0 .12 0 0 0 0 .13 0 0 0 0 .14 1.6 0 0 0 -.62',.02),soil:()=>groundTexture('#6b4a30','.3 0 0 0 .3 .22 0 0 0 .2 .15 0 0 0 .12 0 0 0 0 1','0 0 0 0 .08 0 0 0 0 .05 0 0 0 0 .02 1.5 0 0 0 -.6',.016),concrete:()=>groundTexture('#8d9094','.2 0 0 0 .4 .2 0 0 0 .4 .2 0 0 0 .42 0 0 0 0 1','0 0 0 0 .2 0 0 0 0 .2 0 0 0 0 .21 1.2 0 0 0 -.55',.03)})[kind]();
const treeBody='<ellipse cx="50" cy="91" rx="32" ry="7" fill="#254c3c" opacity=".2"/><path d="M45 48h10v43H45Z" fill="#86613d"/><circle cx="50" cy="34" r="29" fill="#44875a"/><circle cx="31" cy="48" r="23" fill="#36764c"/><circle cx="68" cy="47" r="25" fill="#559969"/>';
Object.assign(extraAssets,{
 'ground-grass':terrain('grass'),'ground-sand':terrain('sand'),'ground-stone':terrain('stone'),'ground-soil':terrain('soil'),'ground-concrete':terrain('concrete'),
  'sky-night':svgAsset(`<defs><linearGradient id="s" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stop-color="#091122"/><stop offset=".7" stop-color="#0f1b33"/><stop offset="1" stop-color="#16243f"/></linearGradient></defs><style>@keyframes tw{0%,100%{opacity:.25}50%{opacity:1}}.t{animation:tw 4s ease-in-out infinite}</style><rect width="1600" height="1000" fill="url(#s)"/>${(()=>{let r=5,o='';const q=()=>(r=(r*16807)%2147483647)/2147483647;for(let i=0;i<90;i++){const x=q()*1600,y=q()*620,z=.6+q()*1.4;o+=`<circle class="${i%3?'':'t'}" style="animation-delay:${(q()*4).toFixed(1)}s" cx="${x.toFixed(0)}" cy="${y.toFixed(0)}" r="${z.toFixed(1)}" fill="#cfe0ff" opacity="${(.3+q()*.5).toFixed(2)}"/>`;}return o;})()}`,1600,1000),
  hills:svgAsset(`<path d="M0 120C200 40 360 100 560 70S900 20 1100 80S1450 40 1600 90V320H0Z" fill="#2c2219"/><path d="M0 120C200 40 360 100 560 70S900 20 1100 80S1450 40 1600 90" fill="none" stroke="#4a3a2a" stroke-width="3" opacity=".6"/><path d="M0 190C240 130 420 200 700 150S1180 120 1380 170S1560 160 1600 150V320H0Z" fill="#1d1610"/>`,1600,320),
  'platform-iso':svgAsset(`<path d="M10 210 400 400V440L10 250Z" fill="#3a2f25"/><path d="M400 400 790 210V250L400 440Z" fill="#2a2119"/><path d="M10 210 400 20 790 210 400 400Z" fill="#54483a"/>${Array.from({length:11},(_,i)=>{const u=(i+1)/12,a=[10+390*u,210-190*u],b=[10+390*u,210+190*u];return `<path d="M${a[0]} ${a[1]}l390 190M${b[0]} ${b[1]}l390 -190" stroke="#8d7a58" stroke-width="1.4" opacity=".32"/>`;}).join('')}<path d="M10 210 400 20 790 210 400 400Z" fill="none" stroke="#a08c66" stroke-width="2" opacity=".55"/><path d="M10 210 400 400 790 210" fill="none" stroke="#6f5d43" stroke-width="2" opacity=".7"/>`,800,520),
  backup:svgAsset(`<ellipse cx="65" cy="140" rx="58" ry="9" fill="#000" opacity=".25"/><path d="M5 40 65 70V140L5 110Z" fill="#e3e8ee"/><path d="M65 70 125 40V110L65 140Z" fill="#c4ccd6"/><path d="M5 40 65 10 125 40 65 70Z" fill="#f6f8fa"/><path d="M52 22 78 22 88 28 62 28Z" fill="#aab4c0"/><g transform="matrix(1 .5 0 1 0 0)"><circle cx="30" cy="62" r="11" fill="#ff7a45"/><circle cx="30" cy="62" r="5" fill="#f6f8fa"/></g>`,130,150),
  sun:svgAsset(`<defs><radialGradient id="h"><stop offset="0" stop-color="#fff2b0" stop-opacity=".95"/><stop offset=".28" stop-color="#ffd25a" stop-opacity=".55"/><stop offset=".62" stop-color="#ffb23a" stop-opacity=".16"/><stop offset="1" stop-color="#ffb23a" stop-opacity="0"/></radialGradient><radialGradient id="c" cx=".4" cy=".38"><stop offset="0" stop-color="#fffbe0"/><stop offset=".55" stop-color="#ffd44d"/><stop offset="1" stop-color="#ff9f1c"/></radialGradient><linearGradient id="r" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stop-color="#ffe27a" stop-opacity="0"/><stop offset="1" stop-color="#ffd25a" stop-opacity=".9"/></linearGradient></defs><style>@keyframes spin{to{transform:rotate(360deg)}}@keyframes pulse{0%,100%{opacity:.8;transform:scale(1)}50%{opacity:1;transform:scale(1.07)}}.r{transform-origin:100px 100px;animation:spin 60s linear infinite}.r2{transform-origin:100px 100px;animation:spin 90s linear infinite reverse}.h{transform-origin:100px 100px;animation:pulse 5s ease-in-out infinite}</style><circle class="h" cx="100" cy="100" r="99" fill="url(#h)"/><g class="r">${Array.from({length:14},(_,i)=>`<path d="M100 100 94 28Q100 8 106 28Z" transform="rotate(${i*360/14} 100 100)" fill="url(#r)"/>`).join('')}</g><g class="r2" opacity=".7">${Array.from({length:10},(_,i)=>`<path d="M100 100 96 36Q100 18 104 36Z" transform="rotate(${18+i*36} 100 100)" fill="url(#r)"/>`).join('')}</g><circle cx="100" cy="100" r="36" fill="url(#c)"/>`,200,200),
  'sun-soft':svgAsset(`<defs><radialGradient id="h"><stop offset="0" stop-color="#ffe9a6"/><stop offset=".35" stop-color="#ffd66e" stop-opacity=".75"/><stop offset="1" stop-color="#ffcf6d" stop-opacity="0"/></radialGradient></defs><style>@keyframes breathe{0%,100%{opacity:.75;transform:scale(.94)}50%{opacity:1;transform:scale(1.06)}}.h{transform-origin:100px 100px;animation:breathe 6s ease-in-out infinite}</style><circle class="h" cx="100" cy="100" r="98" fill="url(#h)"/><circle cx="100" cy="100" r="30" fill="#fff0bd"/>`,200,200),
 moon:svgAsset('<path d="M66 8a42 42 0 1 0 26 62A36 36 0 0 1 66 8Z" fill="#d8e4f2"/>'),
 'moon-full':svgAsset('<circle cx="50" cy="50" r="40" fill="#d8e4f2"/><g fill="#b3c6db"><circle cx="34" cy="32" r="9"/><circle cx="66" cy="57" r="13"/><circle cx="37" cy="71" r="6"/></g>'),
  river:svgAsset(`<defs><linearGradient id="w" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stop-color="#6cc0dc"/><stop offset=".5" stop-color="#3a8fb8"/><stop offset="1" stop-color="#2a6f98"/></linearGradient></defs><style>@keyframes flow{to{stroke-dashoffset:-120}}.f1{stroke-dasharray:16 34;animation:flow 3.2s linear infinite}.f2{stroke-dasharray:10 46;animation:flow 4.6s linear infinite}.f3{stroke-dasharray:22 58;animation:flow 6s linear infinite}</style><path d="M-4 66C120 4 200 130 330 84S520 10 600 36C700 20 800 70 796 112C792 168 690 204 590 176C520 196 450 190 330 168S110 100 -4 150Z" fill="#e4d3a5"/><path d="M-4 76C120 16 200 138 330 94S520 22 600 48C690 34 782 76 780 112C776 158 686 190 592 164C520 184 450 178 330 158S110 92 -4 140Z" fill="url(#w)"/><path class="f1" d="M-4 108C120 52 200 134 330 112S560 60 804 112" fill="none" stroke="#d6f1f8" stroke-width="2.6" stroke-linecap="round" opacity=".7"/><path class="f2" d="M-4 126C120 76 200 150 330 130S560 86 804 128" fill="none" stroke="#bfe6f1" stroke-width="2" stroke-linecap="round" opacity=".55"/><path class="f3" d="M-4 94C120 40 200 118 330 98S560 44 804 96" fill="none" stroke="#ffffff" stroke-width="1.8" stroke-linecap="round" opacity=".5"/>`,800,220),
  'river-wide':svgAsset(`<defs><linearGradient id="w" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stop-color="#6cc0dc"/><stop offset=".5" stop-color="#3a8fb8"/><stop offset="1" stop-color="#2a6f98"/></linearGradient></defs><style>@keyframes flow{to{stroke-dashoffset:-120}}.f1{stroke-dasharray:16 34;animation:flow 3.2s linear infinite}.f2{stroke-dasharray:10 46;animation:flow 4.6s linear infinite}.f3{stroke-dasharray:22 58;animation:flow 6s linear infinite}</style><rect x="-4" y="14" width="808" height="152" rx="0" fill="#e4d3a5"/><rect x="-4" y="26" width="808" height="128" fill="url(#w)"/><path class="f1" d="M-4 64H804" stroke="#d6f1f8" stroke-width="2.6" stroke-linecap="round" opacity=".7" fill="none"/><path class="f2" d="M-4 90H804" stroke="#bfe6f1" stroke-width="2" stroke-linecap="round" opacity=".55" fill="none"/><path class="f3" d="M-4 116H804" stroke="#fff" stroke-width="1.8" stroke-linecap="round" opacity=".5" fill="none"/>`,800,180),
 tree:svgAsset(treeBody),pine:svgAsset('<ellipse cx="50" cy="92" rx="30" ry="6" fill="#254c3c" opacity=".2"/><path d="M46 65h8v28h-8Z" fill="#86613d"/><path d="m50 5 23 36H62l23 33H15l23-33H27Z" fill="#377b60"/><path d="m50 5 23 36H50Z" fill="#509473"/>'),
 forest:svgAsset(`<g transform="translate(45 0) scale(.65)">${treeBody}</g><g transform="translate(3 25) scale(.7)">${treeBody}</g><g transform="translate(80 22) scale(.75)">${treeBody}</g><g transform="translate(42 38) scale(.8)">${treeBody}</g>`,160,120)
});
function canConnect(n){return n&&n.role!=='decoration'&&!domainCatalog.some(([kind])=>kind===n.kind);}
function isGround(n){return n.kind.startsWith('ground-');}
function isBackdrop(n){return n.kind.startsWith('ground-')||n.kind==='platform-iso'||n.kind==='hills'||n.kind==='sky-night';}
function node(id,kind,name,x,y,w,h,fields={}){return{id,kind,name,x,y,w,h,state:'active',value:0,unit:'kW',current:0,currentUnit:'A',efficiency:100,status:'Online',showDetails:false,labelSide:'bottom',labelGap:12,fontSize:16,color:'#293b55',...fields};}
function edge(id,from,to,sourcePort,targetPort,waypoints=[]){return{id,name:id,from,to,sourcePort,targetPort,waypoints,auto:false,state:'active',color:'#6688ff',trackColor:'#c9d7ff',width:5,trackWidth:2.4,radius:12,duration:3.5,direction:1};}
function preset(kind,assets={}){
 const p={format:'flow-studio',version:1,title:'Hybrid energy flow',width:1000,height:650,background:'#ffffff',nodes:[],edges:[],assets:{...clone(assets),...clone(extraAssets)}};
 if(kind==='domain'){
   p.title='المجال · مشهد الطاقة';p.background='#0b1426';p.width=1600;p.height=1000;
   const S=v=>Math.round(v*2/3),N=(id,kind,name,x,y,w,h,f)=>node(id,kind,name,S(x),S(y),S(w),S(h),{showLabel:false,...f}),card=(c,side,gap,icon,f)=>({showLabel:true,labelStyle:'dash',labelSide:side,labelGap:S(gap),fontSize:15,color:c,icon,leader:true,...f});
   p.nodes=[N('sky','sky-night','السماء',1200,750,2400,1500),N('hills','hills','التلال',1200,1260,2400,480),N('platform','platform-iso','المنصة',1200,800,1900,1235),
    N('sun','sun','الشمس',2150,200,300,300),
    N('pv-4','solar','لوح 4',1120,390,300,272,{role:'decoration'}),N('pv-3','solar','لوح 3',980,460,300,272,{role:'decoration'}),N('pv-2','solar','لوح 2',840,530,300,272,{role:'decoration'}),
    N('solar','solar','PV ARRAY • 28.8 kWp',700,600,300,272,card('#ffc23d','left',150,'sun',{value:6.79,unit:'kW',progress:24,status:'Master 3.4 • Slave 1 3.4 kW'})),
    N('home','home','المنزل',930,800,300,193,card('#a78bfa','bottom',70,'home',{title:'HOME • DIRECT',value:4.64,unit:'kW',progress:52,status:'Fed from inverter AC bus'})),
    N('inverter','inverter','2 × S6 HYBRID INVERTER',1220,500,170,133,card('#8ec5ff','top',60,'inverter',{value:5.23,unit:'kW',progress:45,status:'AC output • 48 / 49°C'})),
    N('battery','battery','2 × DYNESS HV',1420,560,92,127,card('#4ade80','top',330,'battery',{value:0,unit:'W',progress:100,status:'SOC 100% / 100% • Idle'})),
    N('grid','grid','METER → SEC GRID',1650,610,110,174,card('#60a5fa','bottom',60,'grid',{value:-593,unit:'W',progress:8,status:'Exporting • Meter'})),
    N('backup','backup','BACKUP LOAD',1370,800,140,162,card('#fb7185','bottom',60,'plug',{value:1.56,unit:'kW',progress:20,status:'Critical loads • EPS'}))];
   p.edges=[edge('solar-inverter','solar','inverter','right','left'),edge('inverter-battery','inverter','battery','right','left'),edge('inverter-home','inverter','home','bottom','top'),edge('inverter-grid','inverter','grid','right','top'),edge('inverter-backup','inverter','backup','bottom','top')];
   const tint={'solar-inverter':'#ffc23d','inverter-battery':'#4ade80','inverter-home':'#a78bfa','inverter-grid':'#60a5fa','inverter-backup':'#fb7185'};p.edges.forEach(e=>{e.auto=true;e.color=tint[e.id];e.trackColor='#2c3548';e.width=4;e.trackWidth=2;e.radius=16;});return p;
 }
 if(kind==='blank'){p.title='Untitled flow';return p;}
 if(kind==='pump'){
  p.title='Solar pump flow';p.nodes=[node('solar','solar','Solar panels',170,180,170,154,{value:6.8,efficiency:92}),node('inverter','inverter','Pump inverter',485,220,150,118,{value:6.2,efficiency:96}),node('pump','pump','Water pump',820,260,150,150,{value:5.9,unit:'kW',status:'Running',current:12.3})];
  p.edges=[edge('solar-inverter','solar','inverter','right','left'),edge('inverter-pump','inverter','pump','right','left')];p.edges.forEach(e=>e.auto=true);return p;
 }
 p.nodes=[node('solar','solar','Solar',285,98,171,155,{value:7.2,labelSide:'right',labelGap:40,status:'PV available'}),node('battery','battery','Battery',100,270,98,135,{value:2.1,status:'Charging'}),node('inverter','inverter','Hybrid inverter',340,315,150,118,{value:5.1,efficiency:96.8}),node('grid','grid','Grid backup',550,525,90,142,{state:'inactive',value:0,status:'',labelGap:0,fontSize:14}),node('home','home','Load',840,265,172,111,{value:3,status:'',labelGap:23}),node('junction','junction','Junction',610,315,8,8,{showLabel:false,status:''})];
 p.edges=[edge('solar','solar','inverter','bottom','top',[[285,228],[340,228]]),edge('battery','battery','inverter','right','left',[[224,270],[224,315]]),edge('inverter','inverter','junction','right','center'),edge('home','junction','home','center','left',[[702,315],[702,265]]),edge('grid','grid','junction','top','center',[[550,382],[610,382]])];
 p.edges[1].direction=-1;p.edges[4].state='inactive';if(kind==='generator'){p.title='Hybrid inverter with generator backup';const n=p.nodes.find(n=>n.id==='grid');n.kind='generator';n.name='Generator backup';n.w=112;n.h=112;n.y=510;}return p;
}
function port(n,p){return p==='left'?[n.x-n.w/2,n.y]:p==='right'?[n.x+n.w/2,n.y]:p==='top'?[n.x,n.y-n.h/2]:p==='bottom'?[n.x,n.y+n.h/2]:[n.x,n.y];}
const direction=p=>({left:[-1,0],right:[1,0],top:[0,-1],bottom:[0,1],center:[0,0]}[p]||[0,0]);
function points(p,e){const a=p.nodes.find(n=>n.id===e.from),b=p.nodes.find(n=>n.id===e.to);if(!a||!b)return[];const s=port(a,e.sourcePort),t=port(b,e.targetPort);
 if(!e.auto)return[s,...e.waypoints.map(v=>[num(v[0]),num(v[1])]),t];
 const d1=direction(e.sourcePort),d2=direction(e.targetPort),s1=[s[0]+d1[0]*30,s[1]+d1[1]*30],t1=[t[0]+d2[0]*30,t[1]+d2[1]*30];let mid=[];
 if(d1[0]&&d2[0]){const x=(s1[0]+t1[0])/2;mid=[[x,s1[1]],[x,t1[1]]];}
 else if(d1[1]&&d2[1]){const y=(s1[1]+t1[1])/2;mid=[[s1[0],y],[t1[0],y]];}
 else mid=d1[1]?[[s1[0],t1[1]]]:[[t1[0],s1[1]]];
 return[s,s1,...mid,t1,t].filter((v,i,a)=>!i||Math.hypot(v[0]-a[i-1][0],v[1]-a[i-1][1])>.01);
}
/* Identical cubic Bézier vertices drive SVG and Lottie. */
function geometry(pts,radius){const clean=pts.filter((p,i,a)=>!i||Math.hypot(p[0]-a[i-1][0],p[1]-a[i-1][1])>.01);const sh={v:[],i:[],o:[],c:false};
 const push=p=>{sh.v.push(p.map(rnd));sh.i.push([0,0]);sh.o.push([0,0]);return sh.v.length-1;};
 if(!clean.length)return sh;push(clean[0]);
 for(let j=1;j<clean.length-1;j++){
  const a=clean[j-1],b=clean[j],c=clean[j+1],l1=Math.hypot(b[0]-a[0],b[1]-a[1]),l2=Math.hypot(c[0]-b[0],c[1]-b[1]);const u=[(b[0]-a[0])/l1,(b[1]-a[1])/l1],v=[(c[0]-b[0])/l2,(c[1]-b[1])/l2];
  const dot=u[0]*v[0]+u[1]*v[1];if(Math.abs(dot)>.9999||radius<=0){push(b);continue;}
  const angle=Math.acos(Math.max(-1,Math.min(1,dot))),tangent=Math.tan(angle/2);const cut=Math.min(radius*tangent,l1/2,l2/2);const k=(4/3)*Math.tan(angle/4)*(cut/tangent);
  const p1=[b[0]-u[0]*cut,b[1]-u[1]*cut],p2=[b[0]+v[0]*cut,b[1]+v[1]*cut],n1=push(p1),n2=push(p2);sh.o[n1]=u.map(x=>rnd(x*k));sh.i[n2]=v.map(x=>rnd(-x*k));
 }
 if(clean.length>1)push(clean.at(-1));return sh;
}
function pathData(sh){if(!sh.v.length)return'';let d=`M${sh.v[0].join(' ')}`;for(let j=1;j<sh.v.length;j++){const a=sh.v[j-1],b=sh.v[j],o=sh.o[j-1],i=sh.i[j];if(o.some(Boolean)||i.some(Boolean))d+=`C${rnd(a[0]+o[0])} ${rnd(a[1]+o[1])} ${rnd(b[0]+i[0])} ${rnd(b[1]+i[1])} ${b.join(' ')}`;else d+=`L${b.join(' ')}`;}return d+(sh.c?'Z':'');}
function opacity(state){return state==='hidden'?0:state==='inactive'?.35:1;}
function labelLines(n){if(n.showLabel===false)return[];const card=n.labelStyle==='card',lines=[];if(n.showName!==false)lines.push({text:n.name,size:n.fontSize,weight:600,color:card?'#bccbda':'#566981'});if(n.showValue!==false)lines.push({text:`${n.value} ${n.unit}`.trim(),size:n.fontSize+6,weight:700,color:n.color});if(n.status&&n.showStatus!==false)lines.push({text:n.status,size:n.fontSize-3,weight:400,color:card?'#bccbda':'#8594a8'});if(n.showDetails)lines.push({text:`${n.current} ${n.currentUnit}  ·  ${n.efficiency}%`,size:n.fontSize-4,weight:400,color:card?'#bccbda':'#8594a8'});return lines;}
let labelContext;
const CARD_ICONS={sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v3M12 19v3M2 12h3M19 12h3M4.9 4.9l2.1 2.1M17 17l2.1 2.1M4.9 19.1 7 17M17 7l2.1-2.1"/>',battery:'<rect x="7" y="4" width="10" height="17" rx="2"/><path d="M10 2h4M13 8l-3 5h4l-3 5"/>',home:'<path d="M3 11 12 3l9 8v10H3z"/><path d="M10 21v-6h4v6"/>',plug:'<path d="M9 2v5M15 2v5M6 7h12v4a6 6 0 0 1-12 0zM12 17v5"/>',grid:'<path d="M12 2 6 22M12 2l6 20M8 9h8M7 15h10M9 6h6"/>',inverter:'<rect x="4" y="3" width="16" height="18" rx="3"/><path d="M7 12c2-4 3-4 5 0s3 4 5 0"/>',pump:'<circle cx="12" cy="12" r="8"/><path d="M12 8v8M8 12h8"/>'};
function measure(text,weight,size,spacing=0){const c=labelContext||(labelContext=document.createElement('canvas').getContext('2d'));c.font=`${weight} ${size}px Arial`;return c.measureText(text).width+spacing*text.length+4;}
function dashParts(n){const s=num(n.fontSize,16)/16;if(n.showLabel===false)return null;const title=(n.title||(n.showName!==false?n.name:''))?String(n.title||n.name).toUpperCase():'',value=n.showValue!==false?`${n.value} ${n.unit}`.trim():'',status=n.status&&n.showStatus!==false?String(n.status):'',details=n.showDetails?`${n.current} ${n.currentUnit}  ·  ${n.efficiency}%`:'',icon=n.icon&&CARD_ICONS[n.icon]?n.icon:'',bar=Number.isFinite(n.progress);if(!title&&!value&&!status&&!details&&!bar)return null;
 const pad=14*s,iconSize=icon?34*s:0,iconW=icon?iconSize+11*s:0,topText=(title?13*s:0)+(value?28*s:0),top=Math.max(topText,iconSize),w=Math.max(150*s,pad*2+Math.max(iconW+Math.max(title?measure(title,600,10*s,.6*s):0,value?measure(value,700,24*s):0),status?measure(status,400,11*s):0,details?measure(details,400,11*s):0)),h=pad*2+top+(bar?14*s:0)+(status?15*s:0)+(details?15*s:0);return{s,title,value,status,details,icon,bar,pad,iconSize,iconW,top,w,h};}
function labelBox(n){if(n.labelStyle==='dash'){const d=dashParts(n);if(!d)return{x:n.x,y:n.y,width:0,height:0,lines:[],pad:0};const side=n.labelSide||'bottom',gap=num(n.labelGap,12);let x=n.x-d.w/2,y=n.y+n.h/2+gap;if(side==='right'){x=n.x+n.w/2+gap;y=n.y-d.h/2;}if(side==='left'){x=n.x-n.w/2-gap-d.w;y=n.y-d.h/2;}if(side==='top')y=n.y-n.h/2-gap-d.h;return{x,y,width:d.w,height:d.h,lines:[{text:n.name,size:n.fontSize,weight:600,color:n.color}],pad:d.pad,dash:d};}const lines=labelLines(n),pad=n.labelStyle==='card'?12:0;const width=Math.max(40,...lines.map(l=>{const c=labelContext||(labelContext=document.createElement('canvas').getContext('2d'));c.font=`${l.weight} ${l.size}px Arial`;return c.measureText(l.text).width+4;}))+pad*2;const height=(lines.length?lines.reduce((s,l)=>s+l.size+9,0)-2:4)+pad*2;
 const side=n.labelSide||'bottom',gap=num(n.labelGap,12);let x=n.x-width/2,y=n.y+n.h/2+gap;if(side==='right'){x=n.x+n.w/2+gap;y=n.y-height/2;}if(side==='left'){x=n.x-n.w/2-gap-width;y=n.y-height/2;}if(side==='top')y=n.y-n.h/2-gap-height;return{x,y,width,height,lines,pad};}
function dashCard(n,b,g){const d=b.dash,s=d.s,c=n.color;g.append(element('rect',{x:b.x,y:b.y,width:b.width,height:b.height,rx:14*s,fill:'#111b2d',stroke:'#2a3b57','stroke-width':1}));let y=b.y+d.pad;const tx=b.x+d.pad+d.iconW;
 if(d.icon){g.append(element('rect',{x:b.x+d.pad,y,width:d.iconSize,height:d.iconSize,rx:9*s,fill:c,'fill-opacity':.16,stroke:c,'stroke-opacity':.45}));const ic=element('g',{transform:`translate(${b.x+d.pad+7*s} ${y+7*s}) scale(${20*s/24})`,fill:'none',stroke:c,'stroke-width':1.8,'stroke-linecap':'round','stroke-linejoin':'round'});ic.innerHTML=CARD_ICONS[d.icon];g.append(ic);}
 let ty=y;if(d.title){g.append(element('text',{x:tx,y:ty+10*s,'font-family':'Arial, sans-serif','font-size':10*s,'font-weight':600,'letter-spacing':.6*s,fill:'#8da2bd'},d.title));ty+=13*s;}
 if(d.value)g.append(element('text',{x:tx,y:ty+22*s,'font-family':'Arial, sans-serif','font-size':24*s,'font-weight':700,fill:'#ffffff'},d.value));
 y+=d.top;if(d.bar){const bw=b.width-d.pad*2;g.append(element('rect',{x:b.x+d.pad,y:y+6*s,width:bw,height:4*s,rx:2*s,fill:'#26364f'}),element('rect',{x:b.x+d.pad,y:y+6*s,width:Math.max(0,bw*n.progress/100),height:4*s,rx:2*s,fill:c}));y+=14*s;}
 if(d.status){g.append(element('text',{x:b.x+d.pad,y:y+11*s,'font-family':'Arial, sans-serif','font-size':11*s,fill:'#a7b6c9'},d.status));y+=15*s;}
 if(d.details)g.append(element('text',{x:b.x+d.pad,y:y+11*s,'font-family':'Arial, sans-serif','font-size':11*s,fill:'#8da2bd'},d.details));return g;}
function leader(n,b){const side=n.labelSide||'bottom',cx=b.x+b.width/2,cy=b.y+b.height/2,a=side==='right'?[b.x,cy]:side==='left'?[b.x+b.width,cy]:side==='top'?[cx,b.y+b.height]:[cx,b.y],g=element('g',{'pointer-events':'none'});g.append(element('path',{d:`M${rnd(a[0])} ${rnd(a[1])}L${rnd(n.x)} ${rnd(n.y)}`,stroke:n.color,'stroke-width':1.6,'stroke-dasharray':'2 5','stroke-linecap':'round',opacity:.75,fill:'none'}),element('circle',{cx:n.x,cy:n.y,r:9,fill:n.color,opacity:.22}),element('circle',{cx:n.x,cy:n.y,r:3.6,fill:n.color}));return g;}
function labels(n){const b=labelBox(n),g=element('g',{'data-label':n.id});if(!b.lines.length)return g;if(b.dash)return dashCard(n,b,g);if(n.labelStyle==='card')g.append(element('rect',{x:b.x,y:b.y,width:b.width,height:b.height,rx:12,fill:'#192633',stroke:'#405064','stroke-width':1}));let y=b.y+b.pad;for(const l of b.lines){y+=l.size;g.append(element('text',{x:b.x+b.width/2,y,'text-anchor':'middle','font-family':'Arial, sans-serif','font-size':l.size,'font-weight':l.weight,fill:l.color},l.text));y+=9;}return g;}
const TILE=256;
function groundFill(parent,n,a,id){const defs=element('defs'),pat=element('pattern',{id,patternUnits:'userSpaceOnUse',x:0,y:0,width:TILE,height:TILE});pat.append(element('image',{x:0,y:0,width:TILE,height:TILE,href:a.src,preserveAspectRatio:'none'}));defs.append(pat);parent.append(defs,element('rect',{x:n.x-n.w/2,y:n.y-n.h/2,width:n.w,height:n.h,fill:`url(#${id})`,'shape-rendering':'crispEdges'}));}
function lengthOf(d){const path=element('path',{d});return path.getTotalLength();}
function render(p,options={}){
 const svg=element('svg',{xmlns:NS,width:p.width,height:p.height,viewBox:`0 0 ${p.width} ${p.height}`,role:'img','aria-label':p.title});svg.append(element('title',{},p.title));
 if(!options.transparent)svg.append(element('rect',{width:p.width,height:p.height,fill:p.background}));
 if(options.grid){const defs=element('defs'),pat=element('pattern',{id:'editor-grid',width:20,height:20,patternUnits:'userSpaceOnUse'});pat.append(element('circle',{cx:1,cy:1,r:.7,fill:'#d1dbea'}));defs.append(pat);svg.append(defs,element('rect',{width:p.width,height:p.height,fill:'url(#editor-grid)','pointer-events':'none'}));}
 const groundLayer=element('g',{'data-layer':'terrain'});svg.append(groundLayer);
 const flowLayer=element('g',{'data-layer':'flows'}),nodeLayer=element('g',{'data-layer':'nodes'});svg.append(flowLayer,nodeLayer);
 for(const e of p.edges){const sh=geometry(points(p,e),e.radius),d=pathData(sh);if(!d)continue;const len=Math.max(1,lengthOf(d));const g=element('g',{'data-edge':e.id,opacity:e.state==='hidden'?0:1,'pointer-events':e.state==='hidden'?'none':undefined});
  if(options.editable){g.append(element('path',{d,stroke:'transparent','stroke-width':20,fill:'none', 'pointer-events':'stroke'}));}
  const track=element('path',{d,fill:'none',stroke:e.trackColor,'stroke-width':e.trackWidth,'stroke-linecap':'round','stroke-linejoin':'round',opacity:e.state==='inactive'?.3:.85});g.append(track);
  if(e.state==='active')for(const glow of [true,false]){const path=element('path',{d,fill:'none',stroke:e.color,'stroke-width':glow?e.width*2.8:e.width,'stroke-linecap':'round','stroke-linejoin':'round',opacity:glow?.13:.95,'stroke-dasharray':`${len*.12} ${len*.88}`,'stroke-dashoffset':-len*e.direction*((options.time||0)%e.duration)/e.duration});
   if(options.animate!==false){path.append(element('animate',{attributeName:'stroke-dashoffset',from:0,to:-len*e.direction,dur:`${e.duration}s`,repeatCount:'indefinite'}));}g.append(path);
  }
  if(options.selection?.type==='edge'&&options.selection.id===e.id){g.append(element('path',{d,fill:'none',stroke:'#3265ef','stroke-width':1,'stroke-dasharray':'4 4','pointer-events':'none'}));if(!e.auto)e.waypoints.forEach((q,j)=>g.append(element('circle',{cx:q[0],cy:q[1],r:6,fill:'#fff',stroke:'#5579ef','stroke-width':2,'data-waypoint':j,'data-edge-id':e.id,cursor:'move'})));}
  flowLayer.append(g);
 }
 for(const n of p.nodes){const g=element('g',{'data-node':n.id,opacity:opacity(n.state),'pointer-events':n.state==='hidden'?'none':undefined}),a=p.assets[n.kind];
  if(a&&isGround(n))groundFill(g,n,a,'ground-pattern-'+p.nodes.indexOf(n));
  else if(a)g.append(element('image',{x:n.x-n.w/2,y:n.y-n.h/2,width:n.w,height:n.h,href:a.src,preserveAspectRatio:'xMidYMid meet'}));
  else g.append(element('rect',{x:n.x-n.w/2,y:n.y-n.h/2,width:n.w,height:n.h,rx:8,fill:'#e5ebf5'}));
  if(n.labelStyle==='dash'&&n.leader!==false){const lb=labelBox(n);if(lb.lines.length)g.append(leader(n,lb));}
  g.append(labels(n));
  if(options.editable){const b=labelBox(n);g.append(element('rect',{x:Math.min(n.x-n.w/2,b.lines.length?b.x:n.x-n.w/2),y:Math.min(n.y-n.h/2,b.lines.length?b.y:n.y-n.h/2),width:Math.max(n.x+n.w/2,b.lines.length?b.x+b.width:n.x+n.w/2)-Math.min(n.x-n.w/2,b.lines.length?b.x:n.x-n.w/2),height:Math.max(n.y+n.h/2,b.lines.length?b.y+b.height:n.y+n.h/2)-Math.min(n.y-n.h/2,b.lines.length?b.y:n.y-n.h/2),fill:'transparent'}));}
  if(options.selection?.type==='node'&&options.selection.id===n.id){g.append(element('rect',{x:n.x-n.w/2-6,y:n.y-n.h/2-6,width:n.w+12,height:n.h+12,rx:8,fill:'none',stroke:'#6488ef','stroke-width':1.5,'stroke-dasharray':'5 4','pointer-events':'none'}));for(const pt of (canConnect(n)?['top','bottom','left','right']:[])){const q=port(n,pt);g.append(element('circle',{cx:q[0],cy:q[1],r:4,fill:'#fff',stroke:'#6488ef','stroke-width':1.5,'pointer-events':'none'}));}}
  (isBackdrop(n)?groundLayer:nodeLayer).append(g);
 }
 return svg;
}
function serialize(svg){return new XMLSerializer().serializeToString(svg);}
function image(src){return new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>reject(new Error('Could not render an embedded image'));im.src=src;});}
async function raster(svg,w,h,scale=1){const c=document.createElement('canvas');c.width=Math.ceil(w*scale);c.height=Math.ceil(h*scale);const ctx=c.getContext('2d'),url=URL.createObjectURL(new Blob([serialize(svg)],{type:'image/svg+xml'}));try{const im=await image(url);ctx.drawImage(im,0,0,c.width,c.height);return c;}finally{URL.revokeObjectURL(url);}}
function dataScript(v){return JSON.stringify(v).replace(/</g,'\\u003c');}
function standalone(p){return`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(p.title)}</title><style>body{margin:0;background:${p.background};font-family:Arial,sans-serif}#flow{width:100%;max-width:${p.width}px;margin:auto}#flow svg{width:100%;height:auto;display:block}body.paused svg{visibility:visible}</style></head><body><div id="flow"></div><script>${standalone.coreSource||''}<\/script><script>const project=${dataScript(p)}; const host=document.getElementById('flow');let paused=matchMedia('(prefers-reduced-motion: reduce)').matches;function draw(){host.replaceChildren(FlowCore.render(project,{animate:!paused}));}function find(list,id){const item=list.find(x=>x.id===id);if(!item)throw new Error('Unknown id: '+id);return item;}window.energyFlow={getProject:()=>FlowCore.clone(project),setNodeState(id,state){if(!FlowCore.STATES.includes(state))throw new Error('Invalid state');find(project.nodes,id).state=state;draw();},setFlowState(id,state){if(!FlowCore.STATES.includes(state))throw new Error('Invalid state');find(project.edges,id).state=state;draw();},setNodeData(id,data){const n=find(project.nodes,id);for(const k of ['name','value','unit','current','currentUnit','efficiency','status','showDetails','showLabel','showName','showValue','showStatus','labelStyle','labelSide','labelGap','fontSize','color'])if(k in data)n[k]=data[k];draw();},setFlowDirection(id,direction){if(direction!==1&&direction!==-1)throw new Error('Direction must be 1 or -1');find(project.edges,id).direction=direction;draw();},pause(){paused=true;host.firstElementChild?.pauseAnimations();},play(){paused=false;host.firstElementChild?.unpauseAnimations();if(!host.querySelector('animate'))draw();}};window.setNodeState=(...a)=>energyFlow.setNodeState(...a);window.setFlowState=(...a)=>energyFlow.setFlowState(...a);window.addEventListener('energy-flow-data',event=>{for(const[id,data]of Object.entries(event.detail.nodes||{}))energyFlow.setNodeData(id,data);for(const[id,state]of Object.entries(event.detail.flows||{}))energyFlow.setFlowState(id,state);});draw();<\/script></body></html>`;}
const stat=k=>({a:0,k});
function ks(pos=[0,0],op=100){return{o:stat(op),r:stat(0),p:stat([...pos,0]),a:stat([0,0,0]),s:stat([100,100,100])};}
function rgb(hex){return[1,3,5].map(i=>parseInt(hex.slice(i,i+2),16)/255);}
function tr(){return{ty:'tr',p:stat([0,0]),a:stat([0,0]),s:stat([100,100]),r:stat(0),o:stat(100),sk:stat(0),sa:stat(0)};}
function animated(a,b,op){return{a:1,k:[{t:0,s:[a],e:[b],o:{x:[0],y:[0]},i:{x:[1],y:[1]}},{t:op,s:[b]}]};}
async function lottie(p,options={}){
 const fps=30;const periods=p.edges.filter(e=>e.state==='active').map(e=>Math.max(1,Math.round(e.duration*fps)));const gcd=(a,b)=>b?gcd(b,a%b):a;let op=periods.reduce((a,b)=>a/gcd(a,b)*b,1);if(!periods.length)op=120;if(!Number.isSafeInteger(op)||op>18000)throw new Error('For a seamless Lottie loop, use matching line cycle durations. The current common loop exceeds 10 minutes.');const seconds=op/fps;
 const out={v:'5.12.2',fr:fps,ip:0,op,w:p.width,h:p.height,nm:p.title,ddd:0,assets:[],layers:[],markers:[]};const layers=[];
 const base=(nm,ty,transform=ks())=>({ddd:0,ty,nm,sr:1,ks:transform,ao:0,ip:0,op,st:0,bm:0});
 const shapeLayer=(nm,it,transform=ks())=>({...base(nm,4,transform),shapes:[{ty:'gr',nm,it:[...it,tr()]}]});
 if(!options.transparent){layers.push(shapeLayer('background',[{ty:'rc',d:1,s:stat([p.width,p.height]),p:stat([p.width/2,p.height/2]),r:stat(0)},{ty:'fl',c:stat(rgb(p.background)),o:stat(100),r:1,bm:0}]));}
 for(const e of p.edges){if(e.state==='hidden')continue;const sh=geometry(points(p,e),e.radius),len=Math.max(1,lengthOf(pathData(sh))),path={ty:'sh',nm:'Rounded route',ks:stat(sh)};
  const stroke=(color,width,opacity,dash)=>({ty:'st',c:stat(rgb(color)),o:stat(opacity),w:stat(width),lc:2,lj:2,ml:4,bm:0,...(dash?{d:dash}:{})});
  layers.push(shapeLayer(`flow-${e.id} • track`,[clone(path),stroke(e.trackColor,e.trackWidth,e.state==='inactive'?30:85)]));
  if(e.state==='active')for(const glow of [true,false]){
   const repeats=op/Math.max(1,Math.round(e.duration*fps));const dash=[{n:'d',nm:'Dash',v:stat(len*.12)},{n:'g',nm:'Gap',v:stat(len*.88)},{n:'o',nm:'Offset',v:animated(0,-len*e.direction*repeats,op)}];
   layers.push(shapeLayer(`flow-${e.id} • ${glow?'glow':'pulse'}`,[clone(path),stroke(e.color,glow?e.width*2.8:e.width,glow?13:95,dash)]));
  }
 }
 const assetMap={};for(const n of p.nodes){if(n.state==='hidden')continue;let a=p.assets[n.kind];if(!a)continue;let ref=assetMap[n.kind];
  if(isGround(n)){const gs=Math.min(1,2048/Math.max(n.w,n.h)),gsvg=element('svg',{xmlns:NS,width:n.w,height:n.h,viewBox:`${n.x-n.w/2} ${n.y-n.h/2} ${n.w} ${n.h}`});groundFill(gsvg,n,a,'gp');const gc=await raster(gsvg,n.w,n.h,gs);a={...a,width:gc.width,height:gc.height};ref='art_'+Object.keys(assetMap).length;assetMap['@'+n.id]=ref;out.assets.push({id:ref,w:gc.width,h:gc.height,u:'',p:gc.toDataURL('image/png'),e:1});}
  else
  if(!ref){ref='art_'+Object.keys(assetMap).length;assetMap[n.kind]=ref;let src=a.src;if(!src.startsWith('data:image/png;')&&!src.startsWith('data:image/jpeg;')){const im=await image(src),c=document.createElement('canvas');c.width=a.width;c.height=a.height;c.getContext('2d').drawImage(im,0,0,c.width,c.height);src=c.toDataURL('image/png');}out.assets.push({id:ref,w:a.width,h:a.height,u:'',p:src,e:1});}
  const scale=Math.min(n.w/a.width,n.h/a.height),w=a.width*scale,h=a.height*scale,transform=ks([n.x-w/2,n.y-h/2],opacity(n.state)*100);transform.s=stat([scale*100,scale*100,100]);layers.push({...base(`node-${n.id} • icon`,2,transform),refId:ref});
  const b=labelBox(n);if(!b.lines.length)continue;const s=element('svg',{xmlns:NS,width:b.width,height:b.height,viewBox:`${b.x} ${b.y} ${b.width} ${b.height}`});s.append(labels(n));const c=await raster(s,b.width,b.height,3),id='label_'+n.id;out.assets.push({id,w:c.width,h:c.height,u:'',p:c.toDataURL('image/png'),e:1});const k=ks([b.x,b.y],opacity(n.state)*100);k.s=stat([100/3,100/3,100]);layers.push({...base(`node-${n.id} • label snapshot`,2,k),refId:id});
 }
 const groundNames=new Set(p.nodes.filter(isBackdrop).flatMap(n=>[`node-${n.id} • icon`,`node-${n.id} • label snapshot`]));const layerOrder=l=>l.nm==='background'?0:groundNames.has(l.nm)?1:2;layers.sort((a,b)=>layerOrder(a)-layerOrder(b));
 out.layers=layers.reverse().map((l,i)=>({...l,ind:i+1}));return out;
}
function sanitizeSVG(text){const doc=new DOMParser().parseFromString(text,'image/svg+xml');if(doc.querySelector('parsererror')||doc.documentElement.localName!=='svg')throw new Error('Invalid SVG');const root=doc.documentElement;
 const allowed=new Set(['svg','g','defs','path','rect','circle','ellipse','line','polyline','polygon','linearGradient','radialGradient','stop','clipPath','mask','pattern','symbol','use','image','text','tspan','title','desc','filter','feGaussianBlur','feOffset','feBlend','feColorMatrix','feMerge','feMergeNode','feComposite','feFlood','feDropShadow','feTurbulence','feDisplacementMap','feComponentTransfer','feFuncR','feFuncG','feFuncB','feFuncA','feMorphology','feTile','feImage','style']);
 const unsafeCSS=v=>/@import|@font-face|expression\s*\(|url\(\s*['"]?(?!#)/i.test(v);for(const el of [...root.querySelectorAll('*')]){if(el.localName==='style'&&unsafeCSS(el.textContent))throw new Error('SVG contains external CSS resources. Embed its assets first.');if(!allowed.has(el.localName)){el.remove();continue;}for(const attr of [...el.attributes]){const k=attr.localName.toLowerCase(),v=attr.value.trim();if(k.startsWith('on')||(k==='style'&&unsafeCSS(v))||((k==='href')&&!v.startsWith('#')&&!/^data:image\/(png|jpeg|gif|webp);base64,/i.test(v))||/url\(\s*['"]?(?!#)/i.test(v))el.removeAttributeNode(attr);}}
 for(const a of [...root.attributes])if(a.localName.toLowerCase().startsWith('on')||(a.localName==='style'&&unsafeCSS(a.value)))root.removeAttributeNode(a);
 return serialize(root);
}
function validate(p){if(!p||p.format!=='flow-studio'||p.version!==1||!Array.isArray(p.nodes)||!Array.isArray(p.edges)||!p.assets)throw new Error('Choose a Flow Studio project JSON. Lottie JSON is an export, not an editable project.');
 if(p.nodes.length>100||p.edges.length>200)throw new Error('Project is too large (100 elements / 200 lines maximum).');
 const finite=(v,min,max)=>Number.isFinite(v)&&v>=min&&v<=max;const color=v=>/^#[\da-f]{6}$/i.test(v);const ids=new Set();
 if(!finite(p.width,100,8192)||!finite(p.height,100,8192)||!color(p.background))throw new Error('Invalid canvas settings');
 for(const n of p.nodes){if(!n||typeof n.id!=='string'||ids.has(n.id)||!finite(n.x,-8192,16384)||!finite(n.y,-8192,16384)||!finite(n.w,1,8192)||!finite(n.h,1,8192)||!STATES.includes(n.state)||!finite(n.fontSize,8,60)||!color(n.color)||!['bottom','top','left','right'].includes(n.labelSide))throw new Error('Invalid element data');if(n.labelStyle!==undefined&&!['text','card','dash'].includes(n.labelStyle))throw new Error('Invalid label style');if(n.icon!==undefined&&!Object.hasOwn(CARD_ICONS,n.icon)&&n.icon!=='')throw new Error('Invalid icon');if(n.progress!==undefined&&!finite(n.progress,0,100))throw new Error('Invalid progress');if(n.leader!==undefined&&typeof n.leader!=='boolean')throw new Error('Invalid leader option');for(const key of ['showLabel','showName','showValue','showStatus','showDetails'])if(n[key]!==undefined&&typeof n[key]!=='boolean')throw new Error('Invalid display option');ids.add(n.id);}
 const edgeIds=new Set();for(const e of p.edges){if(!e||typeof e.id!=='string'||edgeIds.has(e.id)||!ids.has(e.from)||!ids.has(e.to)||!STATES.includes(e.state)||!color(e.color)||!color(e.trackColor)||!finite(e.width,.5,30)||!finite(e.trackWidth,.5,30)||!finite(e.radius,0,100)||!finite(e.duration,.5,20)||![1,-1].includes(e.direction)||!['top','bottom','left','right','center'].includes(e.sourcePort)||!['top','bottom','left','right','center'].includes(e.targetPort)||!Array.isArray(e.waypoints)||e.waypoints.length>80||!e.waypoints.every(q=>Array.isArray(q)&&q.length===2&&q.every(v=>finite(v,-4096,8192))))throw new Error('Invalid line data');if(!canConnect(p.nodes.find(n=>n.id===e.from))||!canConnect(p.nodes.find(n=>n.id===e.to)))throw new Error('Nature elements cannot be connected');edgeIds.add(e.id);}
 for(const[k,a]of Object.entries(p.assets)){if(!a||!finite(a.width,1,10000)||!finite(a.height,1,10000)||typeof a.src!=='string'||!/^data:image\/(png|jpeg|gif|webp|svg\+xml);base64,/i.test(a.src))throw new Error('Project assets must be embedded images');if(a.src.startsWith('data:image/svg+xml;')){const text=decodeURIComponent(escape(atob(a.src.split(',')[1])));a.src='data:image/svg+xml;base64,'+btoa(unescape(encodeURIComponent(sanitizeSVG(text))));}}
 return p;
}
function bounds(p){let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;const take=(x,y)=>{minX=Math.min(minX,x);minY=Math.min(minY,y);maxX=Math.max(maxX,x);maxY=Math.max(maxY,y);};for(const n of p.nodes.filter(n=>n.state!=='hidden')){take(n.x-n.w/2,n.y-n.h/2);take(n.x+n.w/2,n.y+n.h/2);const b=labelBox(n);if(b.lines.length){take(b.x,b.y);take(b.x+b.width,b.y+b.height);}}for(const e of p.edges.filter(e=>e.state!=='hidden'))for(const q of points(p,e)){take(q[0]-e.width*1.4,q[1]-e.width*1.4);take(q[0]+e.width*1.4,q[1]+e.width*1.4);}if(!Number.isFinite(minX))return{minX:0,minY:0,maxX:80,maxY:80,width:100,height:100};return{minX,minY,maxX,maxY,width:Math.ceil(maxX+20),height:Math.ceil(maxY+20)};}
function fit(p){const b=bounds(p),dx=Math.max(0,20-b.minX),dy=Math.max(0,20-b.minY);for(const n of p.nodes){n.x+=dx;n.y+=dy;}for(const e of p.edges)e.waypoints=e.waypoints.map(q=>[q[0]+dx,q[1]+dy]);p.width=Math.min(8192,Math.max(100,b.width+dx));p.height=Math.min(8192,Math.max(100,b.height+dy));return p;}

const api={NS,STATES,clone,esc,num,element,svgAsset,extraAssets,domainCatalog,isGround,canConnect,isBackdrop,node,edge,preset,port,points,geometry,pathData,labelBox,labelLines,labels,opacity,render,serialize,raster,lottie,standalone,validate,sanitizeSVG,bounds,fit};global.FlowCore=api;
})(window);
