/* Project folders are managed by the local Flow Studio server. */
(function(){
'use strict';
const $=id=>document.getElementById(id),F=FlowCore;
let active=null,editing=false,editorProject=null,boardProject=null,timer,pending=Promise.resolve(),loading=false;
const message=text=>$('domain-message').textContent=text;
async function request(path,method='GET',body){const response=await fetch('/api/domain'+path,{method,headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});if(!response.ok){let error;try{error=(await response.json()).error;}catch{}throw new Error(error||'تعذر الوصول إلى ملفات المشروع');}return response.json();}
function compact(){const p=flowStudio.getProject(),kinds=new Set(p.nodes.map(n=>n.kind));p.assets=Object.fromEntries(Object.entries(p.assets).filter(([key])=>kinds.has(key)));return p;}
async function refresh(){if(location.protocol==='file:'){message('لحفظ المشاريع كمجلدات، شغّل python3 server.py من مجلد Flow Studio ثم افتح http://127.0.0.1:8765/#domain');$('domain-create').querySelector('button').disabled=true;return;}try{const data=await request('/projects');$('domain-storage').textContent=data.root;$('domain-create').querySelector('button').disabled=false;const host=$('domain-projects');host.replaceChildren();if(!data.projects.length){const p=document.createElement('p');p.textContent='لا توجد مشاريع بعد. أنشئ مشروعًا لفتح البورد.';host.append(p);}for(const entry of data.projects){const row=document.createElement('article');row.className='domain-project-row';const info=document.createElement('div'),title=document.createElement('h3'),stats=document.createElement('p'),folder=document.createElement('small'),button=document.createElement('button');title.textContent=entry.title;stats.textContent=`${({draft:'مسودة',active:'قيد العمل',complete:'مكتمل'})[entry.status]||'مسودة'} · ${entry.nodes} عنصر · ${entry.edges} رابط · ${entry.assets} أصل · ${new Date(entry.updatedAt).toLocaleString('ar')}`;folder.dir='ltr';folder.textContent=entry.folder;button.textContent='فتح البورد';button.onclick=()=>open(entry.id,button);info.append(title,stats,folder);row.append(info,button);host.append(row);}}catch(e){message(e.message+'\nشغّل python3 server.py وافتح الاستديو من عنوان السيرفر المحلي.');}}
function enter(entry,p){F.validate(p);active=entry;boardProject=p;editorProject=flowStudio.getProject();loading=true;editing=true;flowStudio.setProject(p);flowStudio.resetSession();loading=false;$('domain-folder').textContent=entry.folder;$('domain-status').value=entry.status;$('domain-save-state').textContent='محفوظ في المجلد';document.querySelector('[data-library="elements"]').click();flowScreens.navigate('board');}
async function open(id,button){button.disabled=true;try{await flush();const data=await request('/projects/'+encodeURIComponent(id));enter(data.metadata,data.project);}catch(e){message(e.message);}finally{button.disabled=false;}}
function save(){clearTimeout(timer);timer=null;if(!active||loading)return Promise.resolve();const id=active.id,p=compact(),status=$('domain-status').value;boardProject=p;$('domain-save-state').textContent='جارٍ الحفظ…';$('save-status').textContent='جارٍ الحفظ…';const operation=pending.catch(()=>{}).then(()=>request('/projects/'+encodeURIComponent(id),'PUT',{project:p,status}));pending=operation;operation.then(data=>{if(active?.id===id){active=data.metadata;$('domain-save-state').textContent='محفوظ في المجلد';$('save-status').textContent='محفوظ في المجلد';}}).catch(e=>{if(active?.id===id){$('domain-save-state').textContent='فشل الحفظ، اضغط Save project لإعادة المحاولة';$('save-status').textContent='فشل الحفظ';message(e.message);}});return operation;}
function changed(){if(loading||!editing)return;boardProject=compact();$('domain-save-state').textContent='تغييرات غير محفوظة';clearTimeout(timer);timer=setTimeout(()=>save().catch(()=>{}),650);}
async function flush(){if(timer){clearTimeout(timer);timer=null;await save();}await pending;}
function switchScreen(screen){if(screen==='board'&&active){if(!editing){editing=true;editorProject=flowStudio.getProject();loading=true;flowStudio.setProject(boardProject);flowStudio.resetSession();loading=false;}return;}if(editing){boardProject=compact();save().catch(()=>{});editing=false;loading=true;flowStudio.setProject(editorProject);flowStudio.resetSession();loading=false;}}
$('domain-create').onsubmit=async event=>{event.preventDefault();const button=event.target.querySelector('button');button.disabled=true;message('جارٍ إنشاء مجلد المشروع…');try{await flush();const p=F.preset($('domain-layout').value,window.FLOW_ASSETS);p.title=$('domain-name').value.trim();if(!p.title)throw new Error('اكتب اسم المشروع');const kinds=new Set(p.nodes.map(n=>n.kind));p.assets=Object.fromEntries(Object.entries(p.assets).filter(([key])=>kinds.has(key)));const data=await request('/projects','POST',{project:p,status:'draft'});enter(data.metadata,p);message('');}catch(e){message(e.message);}finally{button.disabled=false;}};
$('domain-refresh').onclick=refresh;$('domain-status').onchange=()=>save().catch(()=>{});
window.addEventListener('beforeunload',event=>{if(timer||$('domain-save-state').textContent==='جارٍ الحفظ…'||$('domain-save-state').textContent.startsWith('فشل')){event.preventDefault();event.returnValue='';}});
window.domainProjects={refresh,save,flush,changed,switchScreen,get active(){return active;},get editing(){return editing;}};
})();
