/* Offline navigation, real asset loading, landing preview, and documentation. */
(function(){
'use strict';
const $=id=>document.getElementById(id),F=window.FlowCore;
const VALID=new Set(['home','editor','domain','board','docs','loading']);let ready=false,failed=false,current='loading',homeRendered=false;
const desired=()=>{const [screen,part]=(location.hash.slice(1)||'home').split('/');return{screen:VALID.has(screen)?screen:'home',part};};
function paintHeader(screen){$('site-header').hidden=screen==='loading';$('editor-header-actions').hidden=screen!=='editor';document.querySelectorAll('[data-screen-link]').forEach(a=>{if(a.dataset.screenLink===screen)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});}
function updateIds(){const body=$('docs-project-ids');if(!body||!window.flowStudio)return;body.replaceChildren();const p=flowStudio.getProject();for(const [type,list]of [['عنصر',p.nodes],['خط',p.edges]])for(const item of list){const row=document.createElement('tr');for(const text of [type,item.name,item.id]){const td=document.createElement('td');if(text===item.id){const code=document.createElement('code');code.dir='ltr';code.textContent=text;td.append(code);}else td.textContent=text;row.append(td);}body.append(row);}if(!p.nodes.length&&!p.edges.length){const row=document.createElement('tr'),cell=document.createElement('td');cell.colSpan=3;cell.textContent='المخطط الحالي فارغ. أضف عناصر من المحرر لعرض معرّفاتها.';row.append(cell);body.append(row);}}
function renderHome(){if(homeRendered)return;const project=F.preset('hybrid',window.FLOW_ASSETS);const reduced=matchMedia('(prefers-reduced-motion:reduce)').matches;const svg=F.render(project,{animate:!reduced});svg.removeAttribute('width');svg.removeAttribute('height');$('home-flow-preview').replaceChildren(svg);homeRendered=true;}
function focusScreen(screen,part){requestAnimationFrame(()=>{if(screen==='docs'&&part){const target=$('doc-'+part);if(target){target.scrollIntoView({behavior:'instant',block:'start'});target.querySelector('h2')?.focus({preventScroll:true});return;}}window.scrollTo({top:0,behavior:'instant'});if(screen==='home')$('home-heading').focus({preventScroll:true});if(screen==='docs')$('docs-heading').focus({preventScroll:true});});}
function route(focus=true){const target=desired();if(!ready){paintHeader('loading');return;}let screen=target.screen;if(screen==='editor'&&target.part==='domain')screen='domain';if(screen==='board'&&!window.domainProjects?.active)screen='domain';window.domainProjects?.switchScreen(screen);current=screen;for(const el of document.querySelectorAll('[data-screen]'))el.hidden=el.dataset.screen!==(screen==='board'?'editor':screen);paintHeader(screen==='board'?'domain':screen);$('editor-header-actions').hidden=!['editor','board'].includes(screen);$('domain-board-bar').hidden=screen!=='board';if(screen==='domain')window.domainProjects.refresh();document.body.classList.remove('booting');document.body.dataset.currentScreen=screen;
 document.documentElement.lang=screen==='editor'?'en':'ar';document.title={home:'Flow Studio — ارسم تدفّق الطاقة',editor:'Flow Studio — Energy diagram editor',domain:'Flow Studio — مشاريع المجال',board:'Flow Studio — بورد المجال',docs:'Flow Studio — دليل الاستخدام',loading:'Flow Studio — Loading'}[screen];
 if(screen==='home')renderHome();if(screen==='docs')updateIds();
 document.querySelectorAll('[data-doc-link]').forEach(a=>{if(a.dataset.docLink===(target.part||'quickstart'))a.setAttribute('aria-current','location');else a.removeAttribute('aria-current');});
 const preview=$('home-flow-preview').firstElementChild;if(preview?.pauseAnimations){if(screen==='home')preview.unpauseAnimations();else preview.pauseAnimations();}
 const canvas=$('canvas');if(canvas?.pauseAnimations){if(['editor','board'].includes(screen))canvas.unpauseAnimations();else canvas.pauseAnimations();}
 if(focus)focusScreen(screen,target.part);
}
async function copy(button){const target=$(button.dataset.copy);if(!target)return;const text=target.textContent,old=button.textContent;try{let copied=false;if(navigator.clipboard?.writeText&&window.isSecureContext){try{await navigator.clipboard.writeText(text);copied=true;}catch(e){/* Local-file browsers may deny the Clipboard API; use the click fallback. */}}if(!copied){const box=document.createElement('textarea');box.value=text;box.dir='ltr';box.style.cssText='position:fixed;top:0;left:-9999px';document.body.append(box);box.focus();box.select();copied=document.execCommand('copy');box.remove();button.focus();}if(!copied)throw new Error('Copy unavailable');button.textContent='تم النسخ';button.setAttribute('aria-label','تم نسخ الكود');setTimeout(()=>{button.textContent=old;button.removeAttribute('aria-label');},1800);}catch(e){button.textContent='حدّد الكود وانسخه';setTimeout(()=>button.textContent=old,2600);}}

document.querySelectorAll('[data-copy]').forEach(button=>button.addEventListener('click',()=>copy(button)));
window.addEventListener('hashchange',()=>route());
function failure(message){failed=true;document.body.classList.add('loading-error');$('loading-heading').textContent='تعذّر تجهيز مساحة العمل';$('loading-message').textContent=message;$('loading-retry').hidden=false;$('loading-continue').hidden=true;}
async function boot(){if(!F||!window.flowStudio||!window.FLOW_ASSETS){failure('أعد فتح المشروع وتأكد من وجود ملفات المصدر معه.');return;}const assets={...window.FLOW_ASSETS,...F.extraAssets},sources=[...new Set(Object.values(assets).map(a=>a.src))];let loaded=0;$('loading-count').textContent=`0 / ${sources.length}`;
 // Decode actual embedded images instead of an artificial loading timer.
 try{await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));await Promise.all(sources.map(src=>new Promise((resolve,reject)=>{const img=new Image();img.onload=async()=>{try{if(img.decode)await img.decode();loaded++;$('loading-progress').value=Math.round(loaded/sources.length*100);$('loading-count').textContent=`${loaded} / ${sources.length}`;resolve();}catch(e){reject(e);}};img.onerror=()=>reject(new Error('Image decode failed'));img.src=src;})));
  ready=true;$('loading-progress').value=100;$('loading-heading').textContent='مساحة العمل جاهزة';$('loading-message').textContent='تم تجهيز المجسمات والخطوط. افتح المحرر وابدأ بمخططك.';$('loading-continue').hidden=false;route();
 }catch(e){failure('تعذّر تحميل إحدى الصور المضمّنة. أعد فتح الملف أو حاول مرة أخرى.');}}
window.flowScreens={navigate(screen,part){if(!VALID.has(screen))throw new Error('Unknown screen');const hash='#'+screen+(part?'/'+part:'');if(location.hash===hash)route();else location.hash=hash;},get ready(){return ready;},get failed(){return failed;},get current(){return current;}};
boot();
})();
