import './model';
import '../src/core.js';
import coreSource from '../src/core.js?raw';
import originalAssets from '../src/assets.json';
import type {Asset, Project, RenderOptions} from './model';
import {portable} from './model';
export const core=window.FlowCore;
core.standalone.coreSource=coreSource;
export const builtins:Record<string,Asset>={...originalAssets,...core.extraAssets};
export const equipment:[string,string][]=[['solar','ألواح شمسية'],['battery','بطارية'],['inverter','عاكس'],['grid','شبكة الكهرباء'],['home','منزل'],['backup','حمل احتياطي'],['generator','مولد'],['pump','مضخة'],['junction','نقطة ربط'],['solar-array','مصفوفة شمسية أيزومترية'],['powerhouse-iso','محطة أيزومترية'],['inverter-wall','جدار عواكس هجينة'],['battery-rack','أبراج بطاريات Dyness'],['bess-iso','تخزين BESS'],['grid-tower-iso','برج شبكة الكهرباء'],['conduit-junction','مفرق مسارات أرضي'],['scene-badge','شارة وصف المشهد'],['iso-solar','ألواح شمسية إيزومتري'],['iso-inverter','عاكس إيزومتري'],['iso-battery','بطارية إيزومتري'],['iso-home','منزل إيزومتري'],['iso-grid','شبكة الكهرباء إيزومتري'],['iso-backup','حمل احتياطي إيزومتري'],['iso-meter','عدّاد إيزومتري']];
export const isoEquipment:Partial<Record<string,{width:number;icon:string}>>={'solar-array':{width:320,icon:'sun'},'powerhouse-iso':{width:220,icon:'home'},'inverter-wall':{width:180,icon:'inverter'},'battery-rack':{width:110,icon:'battery'},'bess-iso':{width:150,icon:'plug'},'grid-tower-iso':{width:140,icon:'grid'},'conduit-junction':{width:40,icon:''},'scene-badge':{width:200,icon:''},'iso-solar':{width:260,icon:'sun'},'iso-inverter':{width:80,icon:'inverter'},'iso-battery':{width:80,icon:'battery'},'iso-home':{width:160,icon:'home'},'iso-grid':{width:140,icon:'grid'},'iso-backup':{width:130,icon:'plug'},'iso-meter':{width:60,icon:'plug'}};
export const isoColor='#8ec5ff';
export const motion:Partial<Record<string,{animation:'spin'|'breathe'|'water';duration:number;options:[string,string][]}>>={'sun-orbit':{animation:'spin',duration:6,options:[['none','بدون حركة'],['spin','دوران حول المركز'],['breathe','نبض ضوئي']]},'river':{animation:'water',duration:4,options:[['none','بدون حركة'],['water','تدفق المياه']]},'river-wide':{animation:'water',duration:4,options:[['none','بدون حركة'],['water','تدفق المياه']]}};
export function createProject(layout:string,title:string){const p={...core.preset(layout,builtins),title};if(layout==='blank'){p.width=2400;p.height=1600;p.background='#899b74';}return portable(p);}
export function checkBounds(p:Project){const b=core.bounds(p);if(b.minX<-.5||b.minY<-.5||b.maxX>p.width+.5||b.maxY>p.height+.5)throw new Error('بعض العناصر خارج البورد. استخدم «ملاءمة مساحة البورد» من الخصائص.');}
export type ExportFormat='lottie'|'html'|'svg'|'png'|'project';
export async function exportProject(p:Project,format:ExportFormat,options:RenderOptions&{scale?:number}={}){const project=core.validate(portable(p));if(format!=='project')checkBounds(project);if(format==='project')return new Blob([JSON.stringify(project,null,2)],{type:'application/json'});if(format==='lottie')return new Blob([JSON.stringify(await core.lottie(project,options))],{type:'application/json'});if(format==='html')return new Blob([core.standalone(project)],{type:'text/html'});if(format==='svg')return new Blob([core.serialize(core.render(project,options))],{type:'image/svg+xml'});if(format!=='png')throw new Error('صيغة تصدير غير مدعومة');if(project.width*project.height*(options.scale||2)**2>32_000_000)throw new Error('اختر دقة PNG أقل أو قلّل مساحة التصدير (الحد 32 مليون بكسل).');const canvas=await core.raster(core.render(project,{...options,animate:false}),project.width,project.height,options.scale||2);return new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('تعذر تصدير الصورة')),'image/png'));}
export function download(blob:Blob,title:string,format:ExportFormat){const name=title.replace(/[^\p{L}\p{N} _-]/gu,'').trim()||'flow';const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name+({lottie:'.lottie.json',project:'.flow.json',html:'.html',svg:'.svg',png:'.png'})[format];a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export async function readAsset(file:File):Promise<Asset>{if(file.size>15*1024*1024)throw new Error('الحد الأقصى للصورة 15 MB');let src:string;if(file.type==='image/svg+xml'||file.name.toLowerCase().endsWith('.svg')){const text=core.sanitizeSVG(await file.text()),doc=new DOMParser().parseFromString(text,'image/svg+xml'),svg=doc.documentElement,view=svg.getAttribute('viewBox')?.trim().split(/[\s,]+/).map(Number);const width=parseFloat(svg.getAttribute('width')||'')||view?.[2]||300,height=parseFloat(svg.getAttribute('height')||'')||view?.[3]||150;if(!Number.isFinite(width)||!Number.isFinite(height)||width<=0||height<=0||width>10000||height>10000)throw new Error('أبعاد SVG غير مدعومة');svg.setAttribute('width',String(width));svg.setAttribute('height',String(height));src='data:image/svg+xml;base64,'+btoa(unescape(encodeURIComponent(new XMLSerializer().serializeToString(svg))));}else{if(!['image/png','image/jpeg','image/gif','image/webp'].includes(file.type))throw new Error('اختر PNG أو JPEG أو GIF أو WebP أو SVG');src=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=()=>reject(new Error('تعذر قراءة الصورة'));r.readAsDataURL(file);});}const img=await new Promise<HTMLImageElement>((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>reject(new Error('ملف الصورة غير صالح'));image.src=src;});const width=img.naturalWidth,height=img.naturalHeight;if(!width||!height||width>10000||height>10000)throw new Error('أبعاد الصورة غير مدعومة');return{src,width,height};}
